# Generated by Django 2.1.8 on 2019-11-28 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Outlet', '0004_auto_20191128_1332'),
        ('Brands', '0005_company_company_landing_imge'),
    ]

    operations = [
        migrations.CreateModel(
            name='backgroundjobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date & Time')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Updation Date & Time')),
                ('Company', models.ForeignKey(blank=True, limit_choices_to={'active_status': '1'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='Brands.Company', verbose_name='Company')),
                ('outlet', models.ForeignKey(blank=True, limit_choices_to={'active_status': '1'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='Outlet.OutletProfile', verbose_name='Outlet')),
            ],
            options={
                'verbose_name': 'backgroundjobs',
                'verbose_name_plural': '  backgroundjobs',
            },
        ),
    ]
