# Generated by Django 2.1.8 on 2019-11-28 10:51

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backgroundjobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='backgroundjobs',
            name='report',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Report'),
        ),
    ]
