# Generated by Django 2.1.8 on 2020-10-03 05:40

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Orders', '0049_auto_20200818_0751'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=200, verbose_name='Client Id')),
                ('client_token', models.CharField(max_length=1000, verbose_name='Client Token')),
            ],
            options={
                'verbose_name': 'Client Details',
                'verbose_name_plural': 'Client Details',
            },
        ),
        migrations.CreateModel(
            name='Order_Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=200, verbose_name='TaskId Details')),
                ('request_id', models.CharField(max_length=200, verbose_name='RequestId Details')),
                ('state', models.CharField(max_length=100, verbose_name='State Details')),
                ('reference_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ReferenceId Details')),
                ('estimated_price', models.FloatField(blank=True, null=True, verbose_name='Estimated Price Details')),
                ('eta', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Pickup Dropoff Details')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Order_Task_Id', to='Orders.Order', verbose_name='OrderId')),
            ],
            options={
                'verbose_name': 'Order Task',
                'verbose_name_plural': 'Order Task',
            },
        ),
        migrations.CreateModel(
            name='Processed_Order_Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='CategoryId Details')),
                ('distance', models.FloatField(blank=True, null=True, verbose_name='Distance Details')),
                ('estimated_price', models.FloatField(blank=True, null=True, verbose_name='Estimated Price Details')),
                ('eta', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Pickup Dropoff Details')),
                ('order_quote_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processed_Order_Quote_Order_Id', to='Orders.Order', verbose_name='OrderId')),
            ],
            options={
                'verbose_name': 'Processed Order Quote',
                'verbose_name_plural': 'Processed Order Quote',
            },
        ),
        migrations.CreateModel(
            name='Task_State_Updates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=200, verbose_name='Event Type Details')),
                ('event_id', models.CharField(max_length=200, verbose_name='Event Id Details')),
                ('task_id', models.CharField(max_length=200, verbose_name='Task Id')),
                ('reference_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='Reference Id Details')),
                ('state', models.CharField(max_length=100, verbose_name='State Details')),
                ('event_timestamp', models.DateTimeField(verbose_name='Event Date & Time')),
                ('eta', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Pickup Dropoff Details')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Price Details')),
                ('total_time', models.FloatField(blank=True, null=True, verbose_name='Total Time')),
                ('cancelled_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cancelled By')),
                ('cancellation_reason', models.CharField(blank=True, max_length=500, null=True, verbose_name='Cancellation Reason')),
                ('runner', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Runner Details')),
                ('request_timestamp', models.DateTimeField(verbose_name='Request Date & Time')),
            ],
            options={
                'verbose_name': 'Task State Updates ',
                'verbose_name_plural': 'Task State Updates',
            },
        ),
        migrations.CreateModel(
            name='Unprocessed_Order_Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_api_response', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Quote Response')),
                ('order_quote_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Unprocessed_Order_Quote_Order_Id', to='Orders.Order', verbose_name='OrderId')),
            ],
            options={
                'verbose_name': 'Unprocessed Order Quote',
                'verbose_name_plural': 'Unprocessed Order Qoute',
            },
        ),
    ]
