# Generated by Django 2.1.8 on 2020-11-09 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dunzo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task_state_updates',
            name='event_timestamp',
        ),
        migrations.RemoveField(
            model_name='task_state_updates',
            name='request_timestamp',
        ),
        migrations.AddField(
            model_name='client_details',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Creation Date & Time'),
        ),
        migrations.AddField(
            model_name='client_details',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Updation Date & Time'),
        ),
        migrations.AddField(
            model_name='order_task',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Creation Date & Time'),
        ),
        migrations.AddField(
            model_name='order_task',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Updation Date & Time'),
        ),
        migrations.AddField(
            model_name='processed_order_quote',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Creation Date & Time'),
        ),
        migrations.AddField(
            model_name='processed_order_quote',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Updation Date & Time'),
        ),
        migrations.AddField(
            model_name='task_state_updates',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Creation Date & Time'),
        ),
        migrations.AddField(
            model_name='task_state_updates',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Updation Date & Time'),
        ),
        migrations.AddField(
            model_name='unprocessed_order_quote',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Creation Date & Time'),
        ),
        migrations.AddField(
            model_name='unprocessed_order_quote',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Updation Date & Time'),
        ),
    ]
