# Generated by Django 2.1.8 on 2020-03-21 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statemaster',
            name='short_name',
            field=models.CharField(default=1, max_length=35, verbose_name='Short Name'),
            preserve_default=False,
        ),
    ]
