# Generated by Django 2.1.8 on 2019-11-03 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_type', models.CharField(max_length=50, unique=True, verbose_name='Business Type')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Description')),
                ('active_status', models.BooleanField(default=1, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date & Time')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Updation Date & Time')),
            ],
            options={
                'verbose_name': '    Brand Type',
                'verbose_name_plural': '    Brand Types',
                'ordering': ['business_type'],
            },
        ),
        migrations.CreateModel(
            name='CurrencyMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(error_messages={'unique': 'Currency already exists with the given name.'}, max_length=30, unique=True, verbose_name='Currency')),
                ('symbol', models.CharField(max_length=20, verbose_name='Symbol')),
                ('codeiso', models.CharField(max_length=4, verbose_name='Code ISO')),
                ('hexsymbol', models.CharField(blank=True, max_length=7, null=True, verbose_name='Hex Symbol')),
                ('active_status', models.BooleanField(default=1, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date & Time')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Updation Date & Time')),
            ],
            options={
                'verbose_name': '   Currency',
                'verbose_name_plural': '   Currencies',
            },
        ),
    ]
