# Generated by Django 2.1.8 on 2019-11-03 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Configuration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currencymaster',
            name='codeiso',
        ),
    ]
