# Generated by Django 2.1.8 on 2020-01-02 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Brands', '0005_company_company_landing_imge'),
        ('Configuration', '0002_remove_currencymaster_codeiso'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Payment Gateway Name')),
                ('username', models.CharField(blank=True, max_length=20, null=True, verbose_name='User Name')),
                ('keyid', models.CharField(blank=True, max_length=20, null=True, verbose_name='keyId')),
                ('keySecret', models.CharField(blank=True, max_length=20, null=True, verbose_name='keySecret')),
                ('symbol', models.CharField(blank=True, max_length=20, null=True, verbose_name='Currency Symbol')),
                ('active_status', models.BooleanField(default=1, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date & Time')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Updation Date & Time')),
                ('company', models.ForeignKey(limit_choices_to={'active_status': '1'}, on_delete=django.db.models.deletion.CASCADE, related_name='PaymentDetails_Company', to='Brands.Company', verbose_name='Company')),
            ],
            options={
                'verbose_name': '   Payment Credential',
                'verbose_name_plural': '   Payment Credential',
            },
        ),
    ]
