# Generated by Django 2.1.8 on 2020-01-22 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Configuration', '0004_colorsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorsetting',
            name='secondaryColor',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Secondary color'),
        ),
        migrations.AddField(
            model_name='colorsetting',
            name='textColor',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Text color'),
        ),
    ]
