# Generated by Django 2.1.8 on 2020-02-03 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Brands', '0006_company_is_sound'),
        ('Configuration', '0008_auto_20200203_2247'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Analytics U Id')),
                ('analytics_snippets', models.TextField(blank=True, null=True, verbose_name='Analytics Snippet')),
                ('active_status', models.BooleanField(default=1, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date & Time')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Updation Date & Time')),
                ('company', models.ForeignKey(limit_choices_to={'active_status': '1'}, on_delete=django.db.models.deletion.CASCADE, related_name='AnalyticsSetting_Company', to='Brands.Company', verbose_name='Company')),
            ],
            options={
                'verbose_name': '   AnalyticsSetting Setting',
                'verbose_name_plural': '   AnalyticsSetting Settings',
            },
        ),
    ]
