# Generated by Django 2.1.8 on 2020-02-05 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Configuration', '0009_analyticssetting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analyticssetting',
            options={'verbose_name': '   Google Analytics Setting', 'verbose_name_plural': '   Google Analytics Settings'},
        ),
    ]
