# Generated by Django 2.1.8 on 2020-02-20 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Brands', '0006_company_is_sound'),
        ('discount', '0009_percentoffers'),
        ('Configuration', '0011_auto_20200205_1911'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title')),
                ('image', models.ImageField(blank=True, null=True, upload_to='EmailSetting', verbose_name='image')),
                ('content', models.CharField(blank=True, max_length=255, null=True, verbose_name='Content')),
                ('thank', models.CharField(blank=True, max_length=255, null=True, verbose_name='thank')),
                ('dis_content', models.CharField(blank=True, max_length=255, null=True, verbose_name='Discount Content')),
                ('active_status', models.BooleanField(default=1, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date & Time')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Updation Date & Time')),
                ('company', models.ForeignKey(limit_choices_to={'active_status': '1'}, on_delete=django.db.models.deletion.CASCADE, related_name='EmailSetting_Company', to='Brands.Company', verbose_name='Company')),
                ('coupon', models.ForeignKey(blank=True, limit_choices_to={'active_status': '1'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='EmailSetting_coupon', to='discount.PercentOffers', verbose_name='Coupon')),
            ],
            options={
                'verbose_name': ' Email Setting',
                'verbose_name_plural': ' Email Settings',
            },
        ),
    ]
