# Generated by Django 2.1.8 on 2020-02-22 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Configuration', '0012_emailsetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Excelimport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title')),
                ('image', models.ImageField(blank=True, null=True, upload_to='import', verbose_name='image')),
                ('active_status', models.BooleanField(default=1, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date & Time')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Updation Date & Time')),
            ],
            options={
                'verbose_name': '   Excel Import',
                'verbose_name_plural': '   Excel Import',
            },
        ),
    ]
