# Generated by Django 2.1.8 on 2020-05-01 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Brands', '0007_company_is_open'),
        ('Outlet', '0015_outletprofile_cam_url'),
        ('Configuration', '0014_auto_20200425_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderFooter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_text', models.TextField(blank=True, null=True, verbose_name='Header Text')),
                ('footer_text', models.TextField(blank=True, null=True, verbose_name='Footer Text')),
                ('gst', models.CharField(blank=True, max_length=50, null=True, verbose_name='GST')),
                ('active_status', models.BooleanField(default=1, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date & Time')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Updation Date & Time')),
                ('company', models.ForeignKey(limit_choices_to={'active_status': '1'}, on_delete=django.db.models.deletion.CASCADE, related_name='HeaderFooter_Company', to='Brands.Company', verbose_name='Company')),
                ('outlet', models.ForeignKey(blank=True, limit_choices_to={'active_status': '1'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='Outlet.OutletProfile', verbose_name='Outlet')),
            ],
            options={
                'verbose_name': '   Receipt Configuration',
                'verbose_name_plural': '   Receipt Configuration',
            },
        ),
    ]
