# Generated by Django 2.1.8 on 2019-11-04 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Brands', '0003_auto_20191103_2319'),
        ('Location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutletMilesRules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Rule Name')),
                ('active_status', models.BooleanField(default=0, verbose_name='Active Status')),
                ('unloaded_miles', models.PositiveIntegerField(verbose_name='Circle Radius in Kms')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date & Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Date & Time')),
            ],
            options={
                'verbose_name': 'Circle Radius Rule',
                'verbose_name_plural': 'Outlet Circle Radius Rule',
            },
        ),
        migrations.CreateModel(
            name='OutletProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='User Name')),
                ('Outletname', models.CharField(max_length=100, unique=True, verbose_name='Outlet Name')),
                ('mobile_with_isd', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Mobile No. with ISD Code')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True, verbose_name='Email Id')),
                ('om_pic', models.ImageField(blank=True, null=True, upload_to='om_profile', verbose_name='Profile Pic')),
                ('password', models.CharField(max_length=20, verbose_name='Password')),
                ('address', models.CharField(max_length=150, verbose_name='Address')),
                ('latitude', models.CharField(max_length=50, verbose_name='Latitude')),
                ('longitude', models.CharField(max_length=50, verbose_name='Longitude')),
                ('active_status', models.BooleanField(default=1, verbose_name='Is Active')),
                ('is_open', models.BooleanField(default=1, verbose_name='Is Open')),
                ('is_company_active', models.BooleanField(default=1, verbose_name='Is Comapny Active')),
                ('opening_time', models.TimeField(blank=True, null=True, verbose_name='Opening Time')),
                ('closing_time', models.TimeField(blank=True, null=True, verbose_name='Closing Time')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date & Time')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Updation Date & Time')),
                ('Company', models.ForeignKey(limit_choices_to={'active_status': '1'}, on_delete=django.db.models.deletion.CASCADE, related_name='OutletProfile_Company', to='Brands.Company', verbose_name='Company')),
                ('area', models.ForeignKey(blank=True, limit_choices_to={'active_status': '1'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='InstaOutletarea_city', to='Location.AreaMaster', verbose_name='Area')),
                ('auth_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instaoutlet_profile_auth_user', to=settings.AUTH_USER_MODEL)),
                ('city', models.ForeignKey(blank=True, limit_choices_to={'active_status': '1'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Outlet_city', to='Location.CityMaster', verbose_name='City')),
            ],
            options={
                'verbose_name': 'Outlet',
                'verbose_name_plural': 'Insta Outlet Profiles',
            },
        ),
        migrations.AddField(
            model_name='outletmilesrules',
            name='Outlet',
            field=models.ForeignKey(limit_choices_to={'active_status': '1'}, on_delete=django.db.models.deletion.CASCADE, related_name='OutletMilesRules_OutletProfile', to='Outlet.OutletProfile', verbose_name='Outlet'),
        ),
    ]
