# Generated by Django 2.1.8 on 2019-11-04 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Outlet', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outletprofile',
            options={'verbose_name': 'Outlet', 'verbose_name_plural': ' Outlet Profiles'},
        ),
    ]
