# Generated by Django 2.1.8 on 2019-11-28 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Outlet', '0003_deliveryboy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveryboy',
            options={'verbose_name': 'DeliveryBoy', 'verbose_name_plural': 'Delivery Person Details'},
        ),
        migrations.AlterModelOptions(
            name='outletmilesrules',
            options={'verbose_name': 'Circle Radius Rule', 'verbose_name_plural': '   Outlet Circle Radius Rule'},
        ),
        migrations.AlterModelOptions(
            name='outletprofile',
            options={'verbose_name': 'Outlet', 'verbose_name_plural': '  Outlet Profiles'},
        ),
        migrations.AlterField(
            model_name='deliveryboy',
            name='is_assign',
            field=models.BooleanField(default=0, verbose_name='Is Assigned'),
        ),
        migrations.AlterField(
            model_name='deliveryboy',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name'),
        ),
    ]
