# Generated by Django 2.1.8 on 2019-11-28 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Outlet', '0004_auto_20191128_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryboy',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
    ]
