# Generated by Django 2.1.8 on 2020-02-12 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserRole', '0001_initial'),
        ('Outlet', '0006_auto_20191209_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='outletprofile',
            name='user_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'active_status': '1'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='OutletProfile_UserType', to='UserRole.UserType', verbose_name='User Type'),
        ),
    ]
