# Generated by Django 2.1.8 on 2020-03-19 13:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Outlet', '0007_outletprofile_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryboy',
            name='Outlet',
        ),
        migrations.AddField(
            model_name='deliveryboy',
            name='outlet_map',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None, verbose_name='Outlet Mapped Ids'),
        ),
    ]
