# Generated by Django 2.1.8 on 2020-03-19 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Outlet', '0008_auto_20200319_1902'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveryboy',
            old_name='outlet_map',
            new_name='outlet',
        ),
    ]
