# Generated by Django 2.1.8 on 2020-04-07 15:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Outlet', '0010_deliveryboy_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='outletprofile',
            name='check_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None, verbose_name='Check List'),
        ),
    ]
