# Generated by Django 2.1.8 on 2020-04-14 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Outlet', '0011_outletprofile_check_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='outletprofile',
            name='is_pos_open',
            field=models.BooleanField(default=1, verbose_name='Is Pos Open'),
        ),
    ]
