# Generated by Django 2.1.8 on 2020-04-15 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Outlet', '0012_outletprofile_is_pos_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='outletprofile',
            name='status',
            field=models.BooleanField(default=1, verbose_name='Is Active'),
        ),
    ]
