# Generated by Django 2.1.8 on 2020-04-15 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Outlet', '0013_outletprofile_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outletprofile',
            name='status',
        ),
    ]
