# Generated by Django 2.1.8 on 2020-04-27 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Outlet', '0014_remove_outletprofile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='outletprofile',
            name='cam_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cam Url'),
        ),
    ]
