# Generated by Django 2.1.8 on 2020-05-24 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Outlet', '0017_temptracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temptracking',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Updated Date & Time'),
        ),
    ]
