# Generated by Django 2.1.8 on 2020-05-25 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Outlet', '0018_auto_20200524_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='temptracking',
            name='outlet',
            field=models.ForeignKey(default=1, limit_choices_to={'active_status': '1'}, on_delete=django.db.models.deletion.CASCADE, related_name='TempTracking_outlet', to='Outlet.OutletProfile', verbose_name='Outlet'),
            preserve_default=False,
        ),
    ]
