# Generated by Django 2.1.8 on 2020-05-27 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Outlet', '0019_temptracking_outlet'),
    ]

    operations = [
        migrations.AddField(
            model_name='temptracking',
            name='is_latest',
            field=models.BooleanField(default=1, verbose_name='Is Latest'),
        ),
    ]
