# Generated by Django 2.1.8 on 2020-06-22 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Outlet', '0020_temptracking_is_latest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outletmilesrules',
            name='active_status',
            field=models.BooleanField(default=1, verbose_name='Active Status'),
        ),
    ]
