# Generated by Django 2.1.8 on 2020-07-12 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Outlet', '0021_auto_20200622_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='temptracking',
            name='SPO2',
            field=models.FloatField(default=1, verbose_name='Oxygen Saturation'),
            preserve_default=False,
        ),
    ]
