# Generated by Django 2.1.8 on 2020-07-12 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Outlet', '0022_temptracking_spo2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temptracking',
            name='SPO2',
            field=models.FloatField(blank=True, null=True, verbose_name='Oxygen Saturation'),
        ),
    ]
