# Generated by Django 2.1.8 on 2020-08-12 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Outlet', '0023_auto_20200712_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outletprofile',
            name='mobile_with_isd',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Mobile No.'),
        ),
    ]
