# Generated by Django 2.1.8 on 2020-09-23 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Outlet', '0025_crustflix_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='outletprofile',
            name='pincode',
            field=models.IntegerField(blank=True, null=True, verbose_name='Pincode'),
        ),
    ]
