# Generated by Django 2.1.8 on 2020-09-24 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Outlet', '0026_outletprofile_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='outletprofile',
            name='gst',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cam Url'),
        ),
    ]
