# Generated by Django 2.1.8 on 2020-10-28 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Outlet', '0027_outletprofile_gst'),
    ]

    operations = [
        migrations.AddField(
            model_name='crustflix_videos',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Updation Date & Time'),
        ),
    ]
