# Generated by Django 2.1.8 on 2020-11-23 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Outlet', '0028_crustflix_videos_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='crustflix_videos',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Title'),
        ),
    ]
