# Generated by Django 2.1.8 on 2021-08-08 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Outlet', '0029_crustflix_videos_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outletprofile',
            name='gst',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='GST'),
        ),
    ]
