# Generated by Django 2.1.8 on 2019-11-03 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Brands', '0002_company_auth_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='auth_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_auth_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
