# Generated by Django 2.1.8 on 2019-11-26 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brands', '0004_auto_20191120_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_landing_imge',
            field=models.ImageField(blank=True, null=True, upload_to='company_banner', verbose_name='Company Banner'),
        ),
    ]
