# Generated by Django 2.1.8 on 2020-01-02 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brands', '0005_company_company_landing_imge'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_sound',
            field=models.BooleanField(default=0, verbose_name='Is Sound'),
        ),
    ]
