# Generated by Django 2.1.8 on 2020-08-12 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brands', '0007_company_is_open'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='contact_person_mobileno',
            field=models.CharField(max_length=15, verbose_name='Contact Mobile No.'),
        ),
    ]
