# Generated by Django 2.1.8 on 2019-11-04 18:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_variant',
            field=models.BooleanField(default=1, verbose_name='Has Variant'),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='Product Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='outlet_map',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None, verbose_name='Outlet Mapped Ids'),
        ),
    ]
