# Generated by Django 2.1.8 on 2019-11-07 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brands', '0003_auto_20191103_2319'),
        ('Product', '0002_auto_20191105_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='category_name',
            field=models.CharField(max_length=50, verbose_name='Category Name'),
        ),
        migrations.AlterUniqueTogether(
            name='productcategory',
            unique_together={('category_name', 'Company')},
        ),
    ]
