# Generated by Django 2.1.8 on 2019-11-08 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_auto_20191107_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addondetails',
            name='product_variant',
            field=models.ForeignKey(blank=True, limit_choices_to={'active_status': '1'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='Product.Variant', verbose_name='Variant'),
        ),
    ]
