# Generated by Django 2.1.8 on 2019-11-17 04:46

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0005_auto_20191108_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='variant_deatils',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
