# Generated by Django 2.1.8 on 2019-11-17 06:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0006_auto_20191117_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='addpn_grp_association',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
    ]
