# Generated by Django 2.1.8 on 2019-11-18 10:19

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0007_auto_20191117_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addondetails',
            name='associated_addons',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
