# Generated by Django 2.1.8 on 2019-11-21 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Brands', '0004_auto_20191120_1650'),
        ('Product', '0008_auto_20191118_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='addondetails',
            name='Company',
            field=models.ForeignKey(default=1, limit_choices_to={'active_status': '1'}, on_delete=django.db.models.deletion.CASCADE, related_name='Addon_Company', to='Brands.Company', verbose_name='Company'),
            preserve_default=False,
        ),
    ]
