# Generated by Django 2.1.8 on 2019-12-03 14:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0012_auto_20191203_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='outlet_map',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None, verbose_name='Outlet Mapped Ids'),
        ),
    ]
