# Generated by Django 2.1.8 on 2019-12-06 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Brands', '0005_company_company_landing_imge'),
        ('Product', '0015_auto_20191206_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Company',
            field=models.ForeignKey(blank=True, limit_choices_to={'active_status': '1'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Product_Company', to='Brands.Company', verbose_name='Company'),
        ),
    ]
