# Generated by Django 2.1.8 on 2019-12-06 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0017_auto_20191206_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Company',
            field=models.ForeignKey(default=1, limit_choices_to={'active_status': '1'}, on_delete=django.db.models.deletion.CASCADE, related_name='Product_Company', to='Brands.Company', verbose_name='Company'),
        ),
    ]
