# Generated by Django 2.1.8 on 2019-12-07 07:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0019_auto_20191206_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category_availability',
            name='available_cat',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None, verbose_name='Available_category ID'),
        ),
        migrations.AlterField(
            model_name='product_availability',
            name='available_product',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None, verbose_name='Available_product ID'),
        ),
    ]
