# Generated by Django 2.1.8 on 2019-12-07 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0020_auto_20191207_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Discount Product Price'),
        ),
    ]
