# Generated by Django 2.1.8 on 2020-02-07 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Brands', '0006_company_is_sound'),
        ('Product', '0021_product_discount_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tag Name')),
                ('tag_image', models.ImageField(blank=True, null=True, upload_to='tag_image/', verbose_name='Image')),
                ('active_status', models.BooleanField(default=0, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date & Time')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Updation Date & Time')),
                ('company', models.ForeignKey(limit_choices_to={'active_status': '1'}, on_delete=django.db.models.deletion.CASCADE, related_name='Tag_Company', to='Brands.Company', verbose_name='Company')),
                ('food_type', models.ForeignKey(limit_choices_to={'active_status': '1'}, on_delete=django.db.models.deletion.CASCADE, related_name='Tag_food', to='Product.FoodType', verbose_name='Food Type')),
            ],
            options={
                'verbose_name': ' Tag',
                'verbose_name_plural': ' Tag',
            },
        ),
    ]
