# Generated by Django 2.1.8 on 2020-02-10 11:46

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Outlet', '0006_auto_20191209_1323'),
        ('Product', '0022_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='featureproduct',
            name='outlet',
            field=models.ForeignKey(default=1, limit_choices_to={'active_status': '1'}, on_delete=django.db.models.deletion.CASCADE, related_name='FeatureProduct_outlet', to='Outlet.OutletProfile', verbose_name='Outlet'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None, verbose_name='Mapped Tag Ids'),
        ),
        migrations.AlterField(
            model_name='featureproduct',
            name='feature_product',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None, verbose_name='Feature_product ID'),
        ),
    ]
