# Generated by Django 2.1.8 on 2020-02-10 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0023_auto_20200210_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featureproduct',
            name='outlet',
            field=models.ForeignKey(blank=True, limit_choices_to={'active_status': '1'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='FeatureProduct_outlet', to='Outlet.OutletProfile', verbose_name='Outlet'),
        ),
    ]
