# Generated by Django 2.1.8 on 2020-02-27 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0026_auto_20200213_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Add-On Name')),
                ('addon_amount', models.FloatField(blank=True, null=True, verbose_name='Add-On Amount')),
                ('priority', models.PositiveIntegerField(blank=True, null=True, verbose_name='Priority')),
                ('active_status', models.BooleanField(default=1, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date & Time')),
                ('addon_group', models.ForeignKey(blank=True, limit_choices_to={'active_status': '1'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addon_gouping', to='Product.AddonDetails', verbose_name='Add-On Group')),
            ],
            options={
                'verbose_name': 'Add-on',
                'verbose_name_plural': '        Add-ons',
            },
        ),
    ]
