# Generated by Django 2.1.8 on 2020-02-27 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Brands', '0006_company_is_sound'),
        ('Product', '0027_addons'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addons',
            options={'verbose_name': 'Add-on', 'verbose_name_plural': '         Add-ons'},
        ),
        migrations.AddField(
            model_name='addons',
            name='Company',
            field=models.ForeignKey(default=1, limit_choices_to={'active_status': '1'}, on_delete=django.db.models.deletion.CASCADE, related_name='Addons_Company', to='Brands.Company', verbose_name='Company'),
            preserve_default=False,
        ),
    ]
