# Generated by Django 2.1.8 on 2020-02-27 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0028_auto_20200227_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addons',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Add-On Name'),
        ),
    ]
