# Generated by Django 2.1.8 on 2020-02-27 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0029_auto_20200227_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='addons',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Updation Date & Time'),
        ),
    ]
