# Generated by Django 2.1.8 on 2020-04-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0033_product_kot_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addons',
            name='identifier',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Add on Identifier'),
        ),
    ]
