# Generated by Django 2.1.8 on 2020-04-25 10:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0034_auto_20200407_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tax_association',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None, verbose_name='Tax Ids'),
        ),
    ]
