# Generated by Django 2.1.8 on 2020-04-26 02:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0035_product_tax_association'),
    ]

    operations = [
        migrations.AddField(
            model_name='addondetails',
            name='priority',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)], verbose_name='Priority'),
        ),
    ]
