# Generated by Django 2.1.8 on 2020-05-07 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0036_addondetails_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_recommended',
            field=models.BooleanField(default=1, verbose_name='Is Recommended'),
        ),
    ]
