# Generated by Django 2.1.8 on 2020-07-29 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0039_auto_20200515_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='addondetails',
            name='is_crust',
            field=models.BooleanField(default=0, verbose_name='Is Crust'),
        ),
    ]
