# Generated by Django 2.1.8 on 2020-10-31 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0042_auto_20201031_0931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addondetails',
            old_name='sync_status',
            new_name='addon_grp_type',
        ),
    ]
