# Generated by Django 2.1.8 on 2020-11-01 11:46

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0043_auto_20201031_0931'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductApiLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Request Data')),
                ('response_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Response Data')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date & Time')),
            ],
            options={
                'verbose_name': ' Product Api Log',
                'verbose_name_plural': ' Product Api Log',
            },
        ),
    ]
