# Generated by Django 2.1.8 on 2020-11-01 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0044_productapilog'),
    ]

    operations = [
        migrations.AddField(
            model_name='productapilog',
            name='request_file',
            field=models.FileField(blank=True, null=True, upload_to='APILogFile/', verbose_name='Request File'),
        ),
    ]
