# Generated by Django 2.1.8 on 2020-11-02 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0046_auto_20201102_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kotsteps',
            name='step_name',
            field=models.CharField(blank=True, choices=[(0, 'Description'), (1, 'Crust'), (2, 'Base Sauce'), (3, 'Toppings'), (4, 'Additional Toppings'), (5, 'Cheese'), (6, 'Extra Cheese'), (7, 'Sauce on Top'), (8, 'Garnishes'), (9, 'Add-ons')], max_length=50, null=True, verbose_name='Step Name'),
        ),
    ]
