# Generated by Django 2.1.8 on 2020-11-02 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0048_auto_20201102_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_desc',
            field=models.TextField(blank=True, null=True, verbose_name='Product Description'),
        ),
    ]
