# Generated by Django 2.1.8 on 2020-11-06 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0050_auto_20201104_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='kotsteps',
            name='variant',
            field=models.ForeignKey(blank=True, limit_choices_to={'active_status': '1'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='KotSteps_variant', to='Product.Variant', verbose_name='Variant'),
        ),
    ]
