# Generated by Django 2.1.8 on 2020-11-07 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0051_kotsteps_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addondetails',
            name='addon_grp_type',
            field=models.CharField(blank=True, choices=[('0', 'Is Crust'), ('1', 'Is Sauce'), ('2', 'Is Cheese'), ('3', 'Is Base Topping'), ('4', 'Is Normal Topping')], max_length=50, null=True, verbose_name='Addon Group Type'),
        ),
    ]
