# Generated by Django 2.1.8 on 2020-12-11 09:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0052_auto_20201107_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='addondetails',
            name='is_zomato_crust',
            field=models.BooleanField(default=0, verbose_name='Is Zomato Crust'),
        ),
        migrations.AddField(
            model_name='addondetails',
            name='zomato_nested_crusts',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None, verbose_name='Mapped Nested Group Ids'),
        ),
    ]
