# Generated by Django 2.1.8 on 2021-01-22 15:56

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Outlet', '0029_crustflix_videos_title'),
        ('Product', '0053_auto_20201211_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='CachedMenuData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date & Time')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Updation Date')),
                ('outlet', models.ForeignKey(blank=True, limit_choices_to={'active_status': '1'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='Outlet.OutletProfile', verbose_name='Outlet')),
            ],
            options={
                'verbose_name': 'Cached Menu Data',
                'verbose_name_plural': 'Cached Menu Data',
            },
        ),
    ]
