# Generated by Django 2.1.8 on 2021-01-22 17:10

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0054_cachedmenudata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cachedmenudata',
            name='menu_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Menu Data'),
        ),
    ]
