# Generated by Django 2.1.8 on 2021-03-02 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0055_auto_20210122_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kotsteps',
            name='step_name',
            field=models.CharField(blank=True, choices=[('0', 'Description'), ('1', 'Crust'), ('2', 'Base Sauce'), ('3', 'Toppings'), ('4', 'Additional Toppings'), ('5', 'Cheese'), ('6', 'Extra Cheese'), ('7', 'Sauce on Top'), ('8', 'Garnishes'), ('9', 'Add-ons'), ('10', 'Fried Filling'), ('11', 'Seasoning')], max_length=50, null=True, verbose_name='Step Name'),
        ),
    ]
