# Generated by Django 2.1.8 on 2019-11-26 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Customers', '0004_auto_20191126_1519'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(max_length=100, unique=True, verbose_name='Notification Type')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Description')),
                ('notification_for', models.CharField(choices=[('customer', 'Customer'), ('admin_user', 'Admin User')], max_length=20, verbose_name='Notification For')),
                ('sample_content', models.TextField(verbose_name='Sample Content')),
                ('active_status', models.BooleanField(default=0, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Updation Date')),
                ('created_by', models.ForeignKey(blank=True, limit_choices_to=models.Q(('is_staff', 0), ('is_superuser', 0), _negated=True), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_config_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(blank=True, limit_choices_to=models.Q(('is_staff', 0), ('is_superuser', 0), _negated=True), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_config_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': '    Notification Type',
                'verbose_name_plural': '    Notification Type',
            },
        ),
        migrations.CreateModel(
            name='NotificationRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_category', models.CharField(choices=[('PUSH', 'PUSH'), ('SMS', 'SMS'), ('EMAIL', 'EMAIL')], max_length=50, verbose_name='Notification Category')),
                ('notification_for', models.CharField(choices=[('Customer', 'Customer'), ('Admin', 'Admin User')], max_length=20, verbose_name='Notification For')),
                ('status', models.BooleanField(choices=[(True, 'Delivered'), (False, 'Undelivered')], verbose_name='Delivery Status')),
                ('reason_for_failed', models.CharField(blank=True, max_length=255, null=True, verbose_name='Reason For Non Delivery')),
                ('message_data', models.CharField(max_length=1000, null=True, verbose_name='Message')),
                ('massge_body', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Content')),
                ('otp', models.CharField(blank=True, max_length=20, null=True, verbose_name='Email OTP')),
                ('motp', models.CharField(blank=True, max_length=20, null=True, verbose_name='Mobile OTP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('is_read', models.BooleanField(default=False, verbose_name='Notification Read Status')),
                ('admin_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_record_admin_user', to=settings.AUTH_USER_MODEL, verbose_name='Admin User Details')),
                ('notification_type', models.ForeignKey(limit_choices_to={'active_status': '1'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='NotificationRecord_notification_configuration', to='Notification.NotificationConfiguration', verbose_name='Notification Type')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_record_user', to='Customers.CustomerProfile', verbose_name='Notification sent to')),
            ],
            options={
                'verbose_name': '  Notification History',
                'verbose_name_plural': '  Notification History',
            },
        ),
    ]
