# Generated by Django 2.1.8 on 2020-04-07 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Outlet', '0010_deliveryboy_company'),
        ('Brands', '0007_company_is_open'),
        ('Orders', '0024_auto_20200323_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSync',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date & Time')),
                ('Company', models.ForeignKey(limit_choices_to={'active_status': '1'}, on_delete=django.db.models.deletion.CASCADE, related_name='OrderSync_Company', to='Brands.Company', verbose_name='Company')),
                ('outlet', models.ForeignKey(blank=True, limit_choices_to={'active_status': '1'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='OrderSync_outlet', to='Outlet.OutletProfile', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'Withrun Order Sync',
                'verbose_name_plural': '       Withrun Order Sync',
            },
        ),
        migrations.CreateModel(
            name='SyncOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date & Time')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SyncOrders_order', to='Orders.Order')),
            ],
            options={
                'verbose_name': 'Withrun Synced Orders',
                'verbose_name_plural': '       Withrun Synced Orders',
            },
        ),
    ]
