# Generated by Django 2.1.8 on 2020-04-13 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Outlet', '0011_outletprofile_check_list'),
        ('withrun', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersync',
            name='last_synced',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Synced Date & Time'),
        ),
        migrations.AddField(
            model_name='syncorders',
            name='outlet',
            field=models.ForeignKey(blank=True, limit_choices_to={'active_status': '1'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SyncOrders_outlet', to='Outlet.OutletProfile', verbose_name='Outlet'),
        ),
        migrations.AlterField(
            model_name='ordersync',
            name='outlet',
            field=models.ForeignKey(blank=True, limit_choices_to={'active_status': '1'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='OrderSync_outlet', to='Outlet.OutletProfile', verbose_name='Outlet'),
        ),
    ]
