# Generated by Django 2.1.8 on 2019-11-22 12:34

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Brands', '0004_auto_20191120_1650'),
        ('Product', '0009_addondetails_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Coupon Type')),
                ('coupon_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Coupon Code')),
                ('frequency', models.PositiveIntegerField(blank=True, null=True, unique=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)], verbose_name='Priority')),
                ('valid_frm', models.DateTimeField(auto_now_add=True, verbose_name='Valid From')),
                ('valid_till', models.DateTimeField(blank=True, null=True, verbose_name='Valid Till')),
                ('product_map', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None, verbose_name='Product Mapped Ids')),
                ('user_map', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), blank=True, null=True, size=None)),
                ('is_min_shop', models.BooleanField(blank=True, null=True, verbose_name='Is Min Shopping Based')),
                ('min_shoping', models.FloatField(blank=True, null=True, verbose_name='Minimum Shopping')),
                ('max_shoping', models.FloatField(blank=True, null=True, verbose_name='Maximum Shopping')),
                ('active_status', models.BooleanField(default=1, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date & Time')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Updation Date & Time')),
                ('Company', models.ForeignKey(limit_choices_to={'active_status': '1'}, on_delete=django.db.models.deletion.CASCADE, related_name='Coupon_Company', to='Brands.Company', verbose_name='Company')),
                ('category', models.ForeignKey(limit_choices_to={'active_status': '1'}, on_delete=django.db.models.deletion.CASCADE, related_name='category_Coupon', to='Product.ProductCategory', verbose_name='category')),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': '   Coupons',
            },
        ),
        migrations.CreateModel(
            name='PercentCombo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcombo_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Combo Name')),
                ('discount_percent', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Discount Percentage')),
                ('valid_frm', models.DateTimeField(auto_now_add=True, verbose_name='Valid From')),
                ('valid_till', models.DateTimeField(blank=True, null=True, verbose_name='Valid Till')),
                ('active_status', models.BooleanField(default=1, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date & Time')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Updation Date & Time')),
                ('discount_product', models.ForeignKey(limit_choices_to={'active_status': '1'}, on_delete=django.db.models.deletion.CASCADE, related_name='D_Product_PercentCombo', to='Product.Product', verbose_name='Discounted Product')),
                ('product', models.ForeignKey(limit_choices_to={'active_status': '1'}, on_delete=django.db.models.deletion.CASCADE, related_name='Product_PercentCombo', to='Product.Product', verbose_name='Main Product')),
            ],
            options={
                'verbose_name': 'Combo',
                'verbose_name_plural': ' Percentage Based Combo',
            },
        ),
        migrations.CreateModel(
            name='QuantityCombo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combo_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Combo Name')),
                ('product_quantity', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)], verbose_name='Product Quantity')),
                ('free_pro_quantity', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)], verbose_name='Free Product Quantity')),
                ('valid_frm', models.DateTimeField(auto_now_add=True, verbose_name='Valid From')),
                ('valid_till', models.DateTimeField(blank=True, null=True, verbose_name='Valid Till')),
                ('active_status', models.BooleanField(default=1, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date & Time')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Updation Date & Time')),
                ('free_product', models.ForeignKey(limit_choices_to={'active_status': '1'}, on_delete=django.db.models.deletion.CASCADE, related_name='F_Product_QuantityCombo', to='Product.Product', verbose_name='Free Product')),
                ('product', models.ForeignKey(limit_choices_to={'active_status': '1'}, on_delete=django.db.models.deletion.CASCADE, related_name='Product_QuantityCombo', to='Product.Product', verbose_name='Main Product')),
            ],
            options={
                'verbose_name': 'Combo',
                'verbose_name_plural': '  Quantity Based Combo',
            },
        ),
    ]
