# Generated by Django 2.1.8 on 2019-11-22 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Brands', '0004_auto_20191120_1650'),
        ('discount', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='percentcombo',
            name='Company',
            field=models.ForeignKey(default=1, limit_choices_to={'active_status': '1'}, on_delete=django.db.models.deletion.CASCADE, related_name='PercentCombo_Company', to='Brands.Company', verbose_name='Company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quantitycombo',
            name='Company',
            field=models.ForeignKey(default=1, limit_choices_to={'active_status': '1'}, on_delete=django.db.models.deletion.CASCADE, related_name='QuantityCombo_Company', to='Brands.Company', verbose_name='Company'),
            preserve_default=False,
        ),
    ]
