# Generated by Django 2.1.8 on 2019-11-22 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0003_auto_20191122_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='is_automated',
            field=models.BooleanField(blank=True, null=True, verbose_name='Is Automated'),
        ),
    ]
