# Generated by Django 2.1.8 on 2019-11-24 06:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0006_auto_20191123_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='frequency',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)], verbose_name='Frequency'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='valid_frm',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Valid From'),
        ),
        migrations.AlterField(
            model_name='percentcombo',
            name='valid_frm',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Valid From'),
        ),
        migrations.AlterField(
            model_name='quantitycombo',
            name='valid_frm',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Valid From'),
        ),
    ]
