# Generated by Django 2.1.8 on 2019-12-17 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0007_auto_20191124_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='category',
            field=models.ForeignKey(blank=True, limit_choices_to={'active_status': '1'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_Coupon', to='Product.ProductCategory', verbose_name='category'),
        ),
    ]
