# Generated by Django 2.1.8 on 2020-02-20 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0009_percentoffers'),
    ]

    operations = [
        migrations.AddField(
            model_name='percentoffers',
            name='valid_till',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Valid Till'),
        ),
        migrations.AlterField(
            model_name='percentoffers',
            name='category',
            field=models.ForeignKey(blank=True, limit_choices_to={'active_status': '1'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PercentOffer_Category', to='Product.ProductCategory', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='percentoffers',
            name='offer_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Coupon Code'),
        ),
    ]
