# Generated by Django 2.1.8 on 2020-03-14 15:15

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0031_addondetails_description'),
        ('Brands', '0007_company_is_open'),
        ('discount', '0011_coupon_outlet_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_type', models.CharField(blank=True, choices=[('Flat', 'Flat'), ('Percentage', 'Percentage')], max_length=20, null=True, verbose_name='Coupon Type')),
                ('frequency', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)], verbose_name='Frequency')),
                ('valid_frm', models.DateTimeField(blank=True, null=True, verbose_name='Valid From')),
                ('valid_till', models.DateTimeField(blank=True, null=True, verbose_name='Valid Till')),
                ('product_map', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None, verbose_name='Product Mapped Ids')),
                ('flat_discount', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)], verbose_name='Flat Discount')),
                ('flat_percentage', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)], verbose_name='Percentage Discount')),
                ('user_map', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), blank=True, null=True, size=None)),
                ('outlet_id', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), blank=True, null=True, size=None)),
                ('is_min_shop', models.BooleanField(blank=True, null=True, verbose_name='Is Min Shopping Based')),
                ('is_reason_required', models.BooleanField(blank=True, null=True, verbose_name='Is Reason Required')),
                ('min_shoping', models.FloatField(blank=True, null=True, verbose_name='Minimum Shopping')),
                ('max_shoping', models.FloatField(blank=True, null=True, verbose_name='Maximum Shopping')),
                ('active_status', models.BooleanField(default=1, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date & Time')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Updation Date & Time')),
                ('Company', models.ForeignKey(limit_choices_to={'active_status': '1'}, on_delete=django.db.models.deletion.CASCADE, related_name='Discount_Company', to='Brands.Company', verbose_name='Company')),
                ('category', models.ForeignKey(blank=True, limit_choices_to={'active_status': '1'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Discount_Coupon', to='Product.ProductCategory', verbose_name='category')),
            ],
            options={
                'verbose_name': 'Discount',
                'verbose_name_plural': '   Discounts',
            },
        ),
    ]
