# Generated by Django 2.1.8 on 2020-03-18 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0013_discountreason'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discount',
            options={'verbose_name': 'discount_name', 'verbose_name_plural': '   discount_name'},
        ),
        migrations.AlterModelOptions(
            name='discountreason',
            options={'verbose_name': 'Discount ', 'verbose_name_plural': '   Discount Reason'},
        ),
        migrations.RemoveField(
            model_name='discount',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='user_map',
        ),
        migrations.AddField(
            model_name='discount',
            name='discount_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Discount Name'),
        ),
        migrations.AddField(
            model_name='discount',
            name='is_all_category',
            field=models.BooleanField(blank=True, default=1, null=True, verbose_name='Is All Category'),
        ),
        migrations.AddField(
            model_name='discount',
            name='user_roll',
            field=models.CharField(blank=True, choices=[('Cashier', 'Cashier'), ('Outlet manager', 'Outlet Manager')], max_length=20, null=True, verbose_name='User Roll'),
        ),
    ]
