# Generated by Django 2.1.8 on 2020-03-18 08:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0014_auto_20200318_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='category',
        ),
        migrations.AddField(
            model_name='discount',
            name='category_map',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None, verbose_name='Category'),
        ),
    ]
