# Generated by Django 2.1.8 on 2020-03-18 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0015_auto_20200318_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='user_roll',
            field=models.CharField(blank=True, choices=[('Cashier', 'Cashier'), ('Outlet Manager', 'Outlet Manager')], max_length=20, null=True, verbose_name='User Roll'),
        ),
    ]
