# Generated by Django 2.1.8 on 2020-03-18 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0017_discount_is_all_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='is_all_category',
            field=models.BooleanField(blank=True, null=True, verbose_name='Is All Category'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='is_all_product',
            field=models.BooleanField(blank=True, null=True, verbose_name='Is All Product'),
        ),
    ]
