# Generated by Django 2.1.8 on 2020-03-27 03:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0018_auto_20200318_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='user_roll',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None, verbose_name='User Roll'),
        ),
    ]
