# Generated by Django 2.1.8 on 2020-12-11 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0019_auto_20200327_0847'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discount',
            options={'verbose_name': 'Discount for POS', 'verbose_name_plural': '   Discount for POS'},
        ),
        migrations.AlterModelOptions(
            name='percentoffers',
            options={'verbose_name': 'Percentage Wise Offer', 'verbose_name_plural': ' Percentage Wise Offer'},
        ),
    ]
