# Generated by Django 2.1.8 on 2020-02-29 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Brands', '0007_company_is_open'),
    ]

    operations = [
        migrations.CreateModel(
            name='Microservice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='User Name')),
                ('password', models.CharField(max_length=20, verbose_name='Password')),
                ('active_status', models.BooleanField(default=0, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date & Time')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Updation Date & Time')),
                ('auth_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Microservice_auth_user', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(limit_choices_to={'active_status': '1'}, on_delete=django.db.models.deletion.CASCADE, related_name='Microservice_Company', to='Brands.Company', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'MicroService',
                'verbose_name_plural': ' Microservice',
            },
        ),
    ]
