# Generated by Django 2.1.8 on 2020-05-24 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('microservice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='microservice',
            name='auth_user',
        ),
        migrations.RemoveField(
            model_name='microservice',
            name='company',
        ),
        migrations.DeleteModel(
            name='Microservice',
        ),
    ]
