# Generated by Django 2.2.5 on 2020-09-07 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Report Name')),
                ('report', models.FileField(blank=True, max_length=200, null=True, upload_to='', verbose_name='Report')),
                ('file_size', models.FloatField(blank=True, max_length=200, null=True, verbose_name='Report Size')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date & Time')),
                ('auth_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_report', to=settings.AUTH_USER_MODEL, verbose_name='User id')),
            ],
            options={
                'verbose_name': 'User_Reports',
                'verbose_name_plural': 'User_Reports',
            },
        ),
    ]
