# Generated by Django 2.1.8 on 2020-09-07 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report',
            field=models.FileField(blank=True, null=True, upload_to='xls_reports/', verbose_name='Report'),
        ),
    ]
