# Generated by Django 2.1.8 on 2020-09-07 18:39

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20200907_2120'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportErrorGenerator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_report', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Error in report generation')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date & Time')),
            ],
            options={
                'verbose_name': '   Error Reports',
                'verbose_name_plural': '   Error Reports',
            },
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'verbose_name': 'User Reports', 'verbose_name_plural': 'User Reports'},
        ),
    ]
