# Generated by Django 2.1.8 on 2020-02-12 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserRole', '0002_auto_20200212_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertype',
            name='user_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='User Type'),
        ),
    ]
