# Generated by Django 2.1.8 on 2020-02-12 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Brands', '0006_company_is_sound'),
        ('UserRole', '0003_auto_20200212_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertype',
            name='Company',
            field=models.ForeignKey(default=1, limit_choices_to={'active_status': '1'}, on_delete=django.db.models.deletion.CASCADE, related_name='UserType_Company', to='Brands.Company', verbose_name='Company'),
            preserve_default=False,
        ),
    ]
