# Generated by Django 2.1.8 on 2020-02-12 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Brands', '0006_company_is_sound'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UserRole', '0004_usertype_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='User Name')),
                ('manager_name', models.CharField(max_length=100, unique=True, verbose_name='Manager Name')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True, verbose_name='Email Id')),
                ('manager_pic', models.ImageField(blank=True, null=True, upload_to='manager_profile', verbose_name='Profile Pic')),
                ('password', models.CharField(max_length=20, verbose_name='Password')),
                ('active_status', models.BooleanField(default=1, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date & Time')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Updation Date & Time')),
                ('Company', models.ForeignKey(limit_choices_to={'active_status': '1'}, on_delete=django.db.models.deletion.CASCADE, related_name='ManagerProfile_Company', to='Brands.Company', verbose_name='Company')),
                ('auth_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ManagerProfile_auth_user', to=settings.AUTH_USER_MODEL)),
                ('user_type', models.ForeignKey(blank=True, limit_choices_to={'active_status': '1'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ManagerProfile_UserType', to='UserRole.UserType', verbose_name='User Type')),
            ],
            options={
                'verbose_name': 'Manager Profile',
                'verbose_name_plural': '  Manager Profiles',
            },
        ),
    ]
