# Generated by Django 2.1.8 on 2020-02-12 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserRole', '0005_managerprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managerprofile',
            name='username',
            field=models.CharField(max_length=100, verbose_name='User Name'),
        ),
    ]
