# Generated by Django 2.1.8 on 2020-02-12 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserRole', '0006_auto_20200212_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managerprofile',
            name='manager_name',
            field=models.CharField(max_length=100, verbose_name='Manager Name'),
        ),
    ]
