# Generated by Django 2.1.8 on 2020-02-13 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserRole', '0008_auto_20200213_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainroutingmodule',
            name='component',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Component'),
        ),
        migrations.AddField(
            model_name='routingmodule',
            name='component',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Component'),
        ),
        migrations.AddField(
            model_name='subroutingmodule',
            name='component',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Component'),
        ),
    ]
