# Generated by Django 2.1.8 on 2020-02-14 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserRole', '0009_auto_20200213_1858'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTypeAuthorization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_status', models.BooleanField(default=1, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date & Time')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Updation Date & Time')),
                ('UserType', models.ForeignKey(blank=True, limit_choices_to={'active_status': '1'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserType_Auth', to='UserRole.UserType', verbose_name='User Type')),
                ('main_route', models.ForeignKey(blank=True, limit_choices_to={'active_status': '1'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RoutingModule_Auth', to='UserRole.MainRoutingModule', verbose_name='Main Module')),
                ('route', models.ForeignKey(blank=True, limit_choices_to={'active_status': '1'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RoutingModule_RoutingAuth', to='UserRole.RoutingModule', verbose_name='Module')),
                ('subroute', models.ForeignKey(blank=True, limit_choices_to={'active_status': '1'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SubRouting_auth', to='UserRole.SubRoutingModule', verbose_name='Sub Module')),
            ],
            options={
                'verbose_name': 'User Type Authorization',
                'verbose_name_plural': '   User Type Authorization',
            },
        ),
    ]
