# Generated by Django 2.1.8 on 2020-02-14 11:21

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserRole', '0012_auto_20200214_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainroutingmodule',
            name='priority',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Priority'),
        ),
        migrations.AddField(
            model_name='routingmodule',
            name='priority',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Priority'),
        ),
        migrations.AddField(
            model_name='subroutingmodule',
            name='priority',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='subroutingmodule',
            name='route',
            field=models.ForeignKey(limit_choices_to={'active_status': '1'}, on_delete=django.db.models.deletion.CASCADE, related_name='SubRoutingModule_RoutingModule', to='UserRole.RoutingModule', verbose_name='Module'),
        ),
        migrations.AlterField(
            model_name='usertypeauthorization',
            name='action_granted',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Action Granted'),
        ),
    ]
