# Generated by Django 2.1.8 on 2020-02-14 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserRole', '0013_auto_20200214_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainroutingmodule',
            name='module_name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Main Module Name'),
        ),
        migrations.AddField(
            model_name='routingmodule',
            name='module_name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Module Name'),
        ),
        migrations.AddField(
            model_name='subroutingmodule',
            name='sub_module_name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Sub-Module Name'),
        ),
    ]
