# Generated by Django 2.1.8 on 2020-02-15 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserRole', '0014_auto_20200214_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertypeauthorization',
            name='main_route',
        ),
        migrations.RemoveField(
            model_name='usertypeauthorization',
            name='route',
        ),
        migrations.RemoveField(
            model_name='usertypeauthorization',
            name='subroute',
        ),
    ]
