# Generated by Django 2.1.8 on 2020-02-15 09:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserRole', '0015_auto_20200215_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertypeauthorization',
            name='main_route',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None, verbose_name='Main Route Ids'),
        ),
        migrations.AddField(
            model_name='usertypeauthorization',
            name='route',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None, verbose_name='Route Ids'),
        ),
        migrations.AddField(
            model_name='usertypeauthorization',
            name='subroute',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None, verbose_name='Sub Route Ids'),
        ),
    ]
