# Generated by Django 2.1.8 on 2020-03-30 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserRole', '0018_rollpermission'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='rollpermission',
        #     name='per_label',
        # ),
        # migrations.AddField(
        #     model_name='rollpermission',
        #     name='label',
        #     field=models.BooleanField(default=0, verbose_name='Label'),
        # ),
    ]
