# Generated by Django 2.1.8 on 2020-04-01 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserRole', '0021_auto_20200330_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingMainRoutingModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_id', models.CharField(max_length=100, unique=True, verbose_name='Module Id')),
                ('module_name', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Main Module Name')),
                ('icon', models.CharField(max_length=100, verbose_name='Icon')),
                ('label', models.CharField(max_length=100, verbose_name='Label')),
                ('to', models.CharField(max_length=100, verbose_name='Url Path')),
                ('component', models.CharField(blank=True, max_length=100, null=True, verbose_name='Component')),
                ('priority', models.PositiveIntegerField(blank=True, null=True, verbose_name='Priority')),
                ('active_status', models.BooleanField(default=1, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date & Time')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Updation Date & Time')),
            ],
            options={
                'verbose_name': 'Main-Module Routing',
                'verbose_name_plural': '     Main-Module Routing',
            },
        ),
        migrations.CreateModel(
            name='BillingRoutingModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Module Name')),
                ('icon', models.CharField(max_length=100, verbose_name='Icon')),
                ('label', models.CharField(max_length=100, verbose_name='Label')),
                ('to', models.CharField(max_length=100, verbose_name='Url Path')),
                ('component', models.CharField(blank=True, max_length=100, null=True, verbose_name='Component')),
                ('priority', models.PositiveIntegerField(blank=True, null=True, verbose_name='Priority')),
                ('active_status', models.BooleanField(default=1, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date & Time')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Updation Date & Time')),
                ('main_route', models.ForeignKey(limit_choices_to={'active_status': '1'}, on_delete=django.db.models.deletion.CASCADE, related_name='BillingRoutingModule_MainRoutingModule', to='UserRole.BillingMainRoutingModule', verbose_name='Main Module')),
            ],
            options={
                'verbose_name': 'Module Routing',
                'verbose_name_plural': '    Module Routing',
            },
        ),
        migrations.CreateModel(
            name='BillingSubRoutingModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_module_name', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Sub-Module Name')),
                ('icon', models.CharField(max_length=100, verbose_name='Icon')),
                ('label', models.CharField(max_length=100, verbose_name='Label')),
                ('to', models.CharField(max_length=100, verbose_name='Url Path')),
                ('component', models.CharField(blank=True, max_length=100, null=True, verbose_name='Component')),
                ('priority', models.PositiveIntegerField(blank=True, null=True, verbose_name='Priority')),
                ('active_status', models.BooleanField(default=1, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date & Time')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Updation Date & Time')),
                ('route', models.ForeignKey(limit_choices_to={'active_status': '1'}, on_delete=django.db.models.deletion.CASCADE, related_name='BillingSubRoutingModule_RoutingModule', to='UserRole.BillingRoutingModule', verbose_name='Module')),
            ],
            options={
                'verbose_name': 'Sub-Module Routing',
                'verbose_name_plural': '   Sub-Module Routing',
            },
        ),
    ]
