# Generated by Django 2.1.8 on 2020-04-01 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserRole', '0022_billingmainroutingmodule_billingroutingmodule_billingsubroutingmodule'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillRollPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.BooleanField(default=0, verbose_name='Label')),
                ('active_status', models.BooleanField(default=1, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date & Time')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Updation Date & Time')),
                ('main_route', models.ForeignKey(limit_choices_to={'active_status': '1'}, on_delete=django.db.models.deletion.CASCADE, related_name='BillRollPermission_main_route', to='UserRole.MainRoutingModule', verbose_name='Main Module')),
                ('user_type', models.ForeignKey(blank=True, limit_choices_to={'active_status': '1'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='BillRollPermission_UserType', to='UserRole.UserType', verbose_name='User Type')),
            ],
            options={
                'verbose_name': 'BillRollPermission',
                'verbose_name_plural': '    BillRollPermission',
            },
        ),
    ]
