# Generated by Django 2.1.8 on 2020-04-01 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserRole', '0023_billrollpermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingmainroutingmodule',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='billingmainroutingmodule',
            name='label',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='billingmainroutingmodule',
            name='module_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Module Id'),
        ),
        migrations.AlterField(
            model_name='billingmainroutingmodule',
            name='to',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Url Path'),
        ),
        migrations.AlterField(
            model_name='billingroutingmodule',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='billingroutingmodule',
            name='label',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='billingroutingmodule',
            name='module_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Module Name'),
        ),
        migrations.AlterField(
            model_name='billingroutingmodule',
            name='to',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Url Path'),
        ),
        migrations.AlterField(
            model_name='billingsubroutingmodule',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='billingsubroutingmodule',
            name='label',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='billingsubroutingmodule',
            name='to',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Url Path'),
        ),
        migrations.AlterField(
            model_name='billrollpermission',
            name='active_status',
            field=models.BooleanField(blank=True, default=1, null=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='billrollpermission',
            name='label',
            field=models.BooleanField(blank=True, default=0, null=True, verbose_name='Label'),
        ),
    ]
