# Generated by Django 2.1.8 on 2020-04-01 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserRole', '0024_auto_20200401_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billrollpermission',
            name='main_route',
            field=models.ForeignKey(limit_choices_to={'active_status': '1'}, on_delete=django.db.models.deletion.CASCADE, related_name='BillRollPermission_main_route', to='UserRole.BillingMainRoutingModule', verbose_name='Main Module'),
        ),
    ]
