# Generated by Django 2.1.8 on 2020-05-16 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Brands', '0007_company_is_open'),
        ('UserRole', '0025_auto_20200401_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='rollpermission',
            name='company',
            field=models.ForeignKey(default=1, limit_choices_to={'active_status': '1'}, on_delete=django.db.models.deletion.CASCADE, related_name='RollPermission_Company', to='Brands.Company', verbose_name='Company'),
            preserve_default=False,
        ),
    ]
