# Generated by Django 2.1.8 on 2020-05-24 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserRole', '0027_billrollpermission_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billingmainroutingmodule',
            options={'verbose_name': 'Billing Main-Module Routing', 'verbose_name_plural': '     Billing Main-Module Routing'},
        ),
        migrations.AlterModelOptions(
            name='billingroutingmodule',
            options={'verbose_name': 'Billing Module Routing', 'verbose_name_plural': '    Billing Module Routing'},
        ),
        migrations.AlterModelOptions(
            name='billingsubroutingmodule',
            options={'verbose_name': 'Billing Sub-Module Routing', 'verbose_name_plural': '   Billing Sub-Module Routing'},
        ),
        migrations.AlterModelOptions(
            name='billrollpermission',
            options={'verbose_name': ' Billing Permission', 'verbose_name_plural': '    Billing Permission'},
        ),
        migrations.AlterModelOptions(
            name='rollpermission',
            options={'verbose_name': 'Permission', 'verbose_name_plural': '    Permission'},
        ),
    ]
