# Generated by Django 2.1.8 on 2020-08-12 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserRole', '0031_downloadtoken'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='downloadtoken',
            options={'verbose_name': 'Download Token', 'verbose_name_plural': 'Download Token'},
        ),
        migrations.RemoveField(
            model_name='downloadtoken',
            name='auth_user',
        ),
        migrations.RemoveField(
            model_name='downloadtoken',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='downloadtoken',
            name='auth_token',
            field=models.CharField(max_length=255, verbose_name='Download Token'),
        ),
    ]
