# Generated by Django 2.1.8 on 2019-11-24 08:12

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('discount', '0007_auto_20191124_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponUsed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Customer Details')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date & Time')),
                ('Coupon', models.ForeignKey(limit_choices_to={'active_status': '1'}, on_delete=django.db.models.deletion.CASCADE, related_name='CouponUsed_coupon', to='discount.Coupon', verbose_name='Coupon')),
            ],
            options={
                'verbose_name': 'Used Coupon',
                'verbose_name_plural': '  Used Coupons',
            },
        ),
    ]
