# Generated by Django 2.1.8 on 2019-11-26 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('History', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponused',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Used At'),
        ),
    ]
