# Generated by Django 2.1.8 on 2019-11-29 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0004_order_has_been_here'),
        ('History', '0002_auto_20191126_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponused',
            name='order_id',
            field=models.ForeignKey(default=1, limit_choices_to={'active_status': '1'}, on_delete=django.db.models.deletion.CASCADE, related_name='CouponUsed_order', to='Orders.Order', verbose_name='Order'),
            preserve_default=False,
        ),
    ]
