# Generated by Django 2.1.8 on 2019-12-02 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Outlet', '0005_auto_20191128_2052'),
        ('Brands', '0005_company_company_landing_imge'),
        ('History', '0003_couponused_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponused',
            name='Company',
            field=models.ForeignKey(default=1, limit_choices_to={'active_status': '1'}, on_delete=django.db.models.deletion.CASCADE, related_name='CouponUsed_Company', to='Brands.Company', verbose_name='Company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='couponused',
            name='outlet',
            field=models.ForeignKey(default=1, limit_choices_to={'active_status': '1'}, on_delete=django.db.models.deletion.CASCADE, related_name='CouponUsed_OutletProfile', to='Outlet.OutletProfile', verbose_name='Outlet'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='couponused',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CouponUsed_order', to='Orders.Order', verbose_name='Order'),
        ),
    ]
