# Generated by Django 2.1.8 on 2020-04-07 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Brands', '0007_company_is_open'),
        ('Outlet', '0010_deliveryboy_company'),
        ('Orders', '0024_auto_20200323_1044'),
        ('History', '0004_auto_20191202_1300'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiderHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Used At')),
                ('Company', models.ForeignKey(limit_choices_to={'active_status': '1'}, on_delete=django.db.models.deletion.CASCADE, related_name='RiderHistory_Company', to='Brands.Company', verbose_name='Company')),
                ('Rider', models.ForeignKey(limit_choices_to={'active_status': '1'}, on_delete=django.db.models.deletion.CASCADE, related_name='RiderHistory_Rider', to='Outlet.DeliveryBoy', verbose_name='Rider')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RiderHistory_order', to='Orders.Order', verbose_name='Order')),
                ('outlet', models.ForeignKey(limit_choices_to={'active_status': '1'}, on_delete=django.db.models.deletion.CASCADE, related_name='RiderHistory_OutletProfile', to='Outlet.OutletProfile', verbose_name='Outlet')),
            ],
            options={
                'verbose_name': 'Rider History',
                'verbose_name_plural': '  Rider History',
            },
        ),
    ]
