# Generated by Django 2.1.8 on 2020-05-14 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Outlet', '0015_outletprofile_cam_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Brands', '0007_company_is_open'),
        ('History', '0005_riderhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutletLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_time', models.DateTimeField(blank=True, null=True, verbose_name='Opening Time')),
                ('closing_time', models.DateTimeField(blank=True, null=True, verbose_name='Closing Time')),
                ('is_open', models.BooleanField(default=1, verbose_name='Is Open')),
                ('Company', models.ForeignKey(limit_choices_to={'active_status': '1'}, on_delete=django.db.models.deletion.CASCADE, related_name='OutletLog_Company', to='Brands.Company', verbose_name='Company')),
                ('auth_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='OutletLog_auth_user', to=settings.AUTH_USER_MODEL)),
                ('outlet', models.ForeignKey(limit_choices_to={'active_status': '1'}, on_delete=django.db.models.deletion.CASCADE, related_name='OutletLog_OutletProfile', to='Outlet.OutletProfile', verbose_name='Outlet')),
            ],
            options={
                'verbose_name': 'OutletLogHistory',
                'verbose_name_plural': '  OutletLog History',
            },
        ),
    ]
