# Generated by Django 2.1.8 on 2020-05-14 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('History', '0006_outletlogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='outletlogs',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Used At'),
            preserve_default=False,
        ),
    ]
