# Generated by Django 2.1.8 on 2020-02-15 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        # migrations.CreateModel(
        #     name='POSOrder',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('created_on', models.DateTimeField(blank=True, null=True, verbose_name='Created On')),
        #         ('customer_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Customet Name')),
        #         ('customer_number', models.CharField(blank=True, max_length=150, null=True, verbose_name='customer_number')),
        #         ('date', models.DateTimeField(blank=True, null=True, verbose_name='Date')),
        #         ('discount_value', models.FloatField(blank=True, null=True, verbose_name='Discount Value')),
        #         ('external_id', models.CharField(blank=True, max_length=150, null=True, verbose_name='External ID')),
        #         ('ids', models.CharField(blank=True, max_length=150, null=True, verbose_name='IDs')),
        #         ('invoice_number', models.CharField(blank=True, max_length=150, null=True, verbose_name='Invoice Number')),
        #         ('order_type', models.CharField(blank=True, max_length=150, null=True, verbose_name='Order Type')),
        #         ('outlet', models.CharField(blank=True, max_length=150, null=True, verbose_name='Outlet')),
        #         ('payment_mode', models.CharField(blank=True, max_length=150, null=True, verbose_name='Payment Mode')),
        #         ('rider_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Rider Name')),
        #         ('rider_number', models.CharField(blank=True, max_length=150, null=True, verbose_name='Rider Number')),
        #         ('source', models.CharField(blank=True, max_length=150, null=True, verbose_name='Source')),
        #         ('status_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Status Name')),
        #         ('sub_total', models.FloatField(blank=True, null=True, verbose_name='Sub Total')),
        #         ('time', models.TimeField(blank=True, null=True, verbose_name='Time')),
        #         ('total', models.FloatField(blank=True, null=True, verbose_name='Total')),
        #         ('subtotal', models.FloatField(blank=True, null=True, verbose_name='Sub Total')),
        #         ('total_tax', models.FloatField(blank=True, null=True, verbose_name='Total Tax')),
        #         ('user_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='User Name')),
        #     ],
        #     options={
        #         'verbose_name': 'POS Management',
        #         'verbose_name_plural': ' POS Management',
        #     },
        # ),
    ]
