# Generated by Django 2.1.8 on 2019-11-21 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Brands', '0004_auto_20191120_1650'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='customer_otp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_OTP', models.CharField(blank=True, max_length=10, null=True, verbose_name='Mobile OTP')),
                ('email_OTP', models.CharField(blank=True, max_length=10, null=True, verbose_name='Email OTP')),
                ('is_mobile_verified', models.BooleanField(default=False, verbose_name='Is Mobile Number Verified')),
                ('is_email_verfied', models.BooleanField(default=False, verbose_name='Is Email Verified')),
                ('is_email_otp_used', models.BooleanField(default=False, verbose_name='Is Email OTP Used')),
                ('is_mob_otp_used', models.BooleanField(default=False, verbose_name='Is Mobile OTP Used')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
            ],
            options={
                'verbose_name': ' Customer OTP',
                'verbose_name_plural': ' Customer OTP',
            },
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='User Name')),
                ('pass_pin', models.CharField(max_length=20, verbose_name='Pin')),
                ('mobile_with_isd', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Mobile No. with ISD Code')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email Id')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='customer_profile', verbose_name='Profile Pic')),
                ('address', models.CharField(max_length=150, verbose_name='Address')),
                ('latitude', models.CharField(max_length=50, verbose_name='Latitude')),
                ('longitude', models.CharField(max_length=50, verbose_name='Longitude')),
                ('active_status', models.BooleanField(default=1, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date & Time')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Updation Date & Time')),
                ('Company', models.ForeignKey(limit_choices_to={'active_status': '1'}, on_delete=django.db.models.deletion.CASCADE, related_name='CustomerProfile_Company', to='Brands.Company', verbose_name='Company')),
                ('auth_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CustomerProfile_auth_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': ' Customer Profiles',
            },
        ),
        migrations.AddField(
            model_name='customer_otp',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_customer', to='Customers.CustomerProfile', verbose_name='Customer'),
        ),
    ]
