# Generated by Django 2.1.8 on 2019-11-21 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer_otp',
            options={'verbose_name': ' Customer OTP', 'verbose_name_plural': 'Customer OTP'},
        ),
    ]
