# Generated by Django 2.1.8 on 2020-02-03 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0004_auto_20191126_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Mobile No'),
        ),
    ]
