# Generated by Django 2.1.8 on 2020-02-17 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0005_auto_20200203_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='is_pos',
            field=models.BooleanField(default=0, verbose_name='Is Pos'),
        ),
    ]
