# Generated by Django 2.1.8 on 2020-03-03 13:52

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0006_customerprofile_is_pos'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='address1',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Address1'),
        ),
    ]
