"""
Django settings for zapio project.

Generated by 'django-admin startproject' using Django 2.1.8.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os
import json
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

real_path = os.path.dirname(os.path.realpath(__file__))
env_path = os.path.dirname((os.path.dirname(real_path)))
env_file = open(env_path+'/Env.json')
env_data = json.load(env_file)

#if 1 then local,
#if 2 then remote connection with staging
#if 3 then remote connection with live
#if 4 then staging
#if 5 then live
creds_flag = env_data["env_flag"]
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
if creds_flag == 5:
    f = open(BASE_DIR+'/zapio/'+'secrets.json',)
else:
    f = open(BASE_DIR+'/zapio/'+'staging_secrets.json',)
universal_data = json.load(f)
SECRET_KEY = universal_data["secret_key"]

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = universal_data["debug_flag"]

ALLOWED_HOSTS = universal_data["ALLOWED_HOSTS"]


# Application definition

INSTALLED_APPS = [
    'jet.dashboard',
    'jet',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'rest_framework_swagger',
    'rest_framework_tracking',
    'corsheaders',
    'Configuration',
    'Product',
    'Location',
    'Brands',
    'Outlet',
    'Customers',
    'discount',
    'Orders',
    'CustomerApi',
    'History',
    'Notification',
    'OutletApi',
    'backgroundjobs',
    'HistoryApi',
    'kitchen',
    'pos',
    'UserRole',
    'PosApi',
    'urbanpiper',
    'microservice',
    'MicroApi',
    'drf_yasg',
    'reports',
    'withrun',
    'django_crontab',
    'django_cleanup',
    'Dunzo'
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.locale.LocaleMiddleware',
]

ROOT_URLCONF = 'zapio.urls'

REST_FRAMEWORK = {
    
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '70/second',
        'user': '70/second'
    },

   'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
   ),
   'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.AllowAny',
    ),
   'DEFAULT_SCHEMA_CLASS': 'rest_framework.schemas.coreapi.AutoSchema' 
}


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

CORS_ORIGIN_ALLOW_ALL = True
WSGI_APPLICATION = 'zapio.wsgi.application'



CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'my_cache_table',
        'TIMEOUT': 120,
        'OPTIONS': {
            'MAX_ENTRIES': 1000
        }
    }
}


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

try:
    from zapio.database_settings import *
except Exception as e:
    print(e)


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

FILE_UPLOAD_HANDLERS = [
    'django.core.files.uploadhandler.TemporaryFileUploadHandler',
]
# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/


CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'token'
]

LANGUAGE_CODE = 'en-us'

# LANGUAGE_CODE = 'de-de'
# LANGUAGES = [
#     ('de')
# ]


TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

MEDIA_URL = '/media/'
STATIC_URL = '/static/'

STATICFILES_DIRS = (
  os.path.join(BASE_DIR, 'static/'),
)

JQUERY_URL = True
# JQUERY_URL = False

JET_SIDE_MENU_COMPACT = False


Media_Path = "https://admin.instapos.in/media/"
# Media_Path = "http://admin.instapos.in:8080/media/"


CRONJOBS = [
    ('*/59 * * * *', 'backgroundjobs.order_mgr_bot.order_process_log'),
    ('15 1 * * *', 'backgroundjobs.automail.automail_sales_report_mgr'),
    ('30 13 * * *', 'backgroundjobs.automail.automail_rhi_report_mgr'),
    ('*/30 * * * *', 'backgroundjobs.invoice_mgr_bot.invoice_mgr')
    
]

