# Generated by Django 2.1.8 on 2020-01-10 14:09

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Brands', '0006_company_is_sound'),
        ('Product', '0021_product_discount_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Ingredient name')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Ingredient', verbose_name='Ingredient Image')),
                ('active_status', models.BooleanField(default=0, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date & Time')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Updation Date & Time')),
                ('company', models.ForeignKey(limit_choices_to={'active_status': '1'}, on_delete=django.db.models.deletion.CASCADE, related_name='Ingredient_Company', to='Brands.Company', verbose_name='Company')),
                ('food_type', models.ForeignKey(limit_choices_to={'active_status': '1'}, on_delete=django.db.models.deletion.CASCADE, related_name='Ingredient_food', to='Product.FoodType', verbose_name='Food Type')),
            ],
            options={
                'verbose_name': 'Ingredient',
                'verbose_name_plural': ' Ingredient',
            },
        ),
        migrations.CreateModel(
            name='StepToprocess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ingredient', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
                ('process', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name Of Process')),
                ('time_of_process', models.CharField(blank=True, max_length=100, null=True, verbose_name='Time Of Process')),
                ('image_of_process', models.ImageField(blank=True, null=True, upload_to='ImageProcess', verbose_name='Image Of Process')),
                ('active_status', models.BooleanField(default=0, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date & Time')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Updation Date & Time')),
                ('company', models.ForeignKey(limit_choices_to={'active_status': '1'}, on_delete=django.db.models.deletion.CASCADE, related_name='StepToprocess_Company', to='Brands.Company', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'StepToprocess',
                'verbose_name_plural': ' StepToProcess',
            },
        ),
    ]
