# Generated by Django 2.1.8 on 2020-01-14 08:17

import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0021_product_discount_price'),
        ('kitchen', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='steptoprocess',
            name='image_of_process',
        ),
        migrations.AddField(
            model_name='steptoprocess',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='steptoprocess',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Stepprocess', verbose_name='Image Of Process'),
        ),
        migrations.AddField(
            model_name='steptoprocess',
            name='product',
            field=models.ForeignKey(default=1, limit_choices_to={'active_status': '1'}, on_delete=django.db.models.deletion.CASCADE, related_name='StepToprocess_product', to='Product.Product', verbose_name='Product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='steptoprocess',
            name='step',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)], verbose_name='Step'),
        ),
        migrations.AddField(
            model_name='steptoprocess',
            name='varient',
            field=models.ForeignKey(default=1, limit_choices_to={'active_status': '1'}, on_delete=django.db.models.deletion.CASCADE, related_name='StepToprocess_varient', to='Product.Variant', verbose_name='Variant'),
            preserve_default=False,
        ),
        # migrations.AlterField(
        #     model_name='steptoprocess',
        #     name='Ingredient',
        #     field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=models.TextField()),
        # ),
    ]
