# Generated by Django 2.1.8 on 2020-01-14 08:26

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0003_remove_steptoprocess_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='steptoprocess',
            name='ingredient',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
