# Generated by Django 2.1.8 on 2020-01-17 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0010_orderstatustype_can_process'),
        ('Brands', '0006_company_is_sound'),
        ('kitchen', '0004_steptoprocess_ingredient'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_status', models.CharField(blank=True, choices=[('0', 'Not Started'), ('1', 'In Progress'), ('2', 'Completed')], max_length=100, null=True, verbose_name='Process Status')),
                ('started_at', models.TimeField(blank=True, null=True, verbose_name='Start Time')),
                ('completed_at', models.TimeField(blank=True, null=True, verbose_name='Completion Time')),
                ('Order', models.ForeignKey(limit_choices_to={'active_status': '1'}, on_delete=django.db.models.deletion.CASCADE, related_name='ProcessTrack_Order', to='Orders.Order', verbose_name='Variant')),
                ('Step', models.ForeignKey(limit_choices_to={'active_status': '1'}, on_delete=django.db.models.deletion.CASCADE, related_name='ProcessTrack_product', to='kitchen.StepToprocess', verbose_name='Product')),
                ('company', models.ForeignKey(limit_choices_to={'active_status': '1'}, on_delete=django.db.models.deletion.CASCADE, related_name='ProcessTrack_Company', to='Brands.Company', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'ProcessTrack',
                'verbose_name_plural': ' ProcessTrack',
            },
        ),
    ]
