# Generated by Django 2.1.8 on 2020-01-17 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0021_product_discount_price'),
        ('kitchen', '0005_processtrack'),
    ]

    operations = [
        migrations.AddField(
            model_name='processtrack',
            name='product',
            field=models.ForeignKey(default=1, limit_choices_to={'active_status': '1'}, on_delete=django.db.models.deletion.CASCADE, related_name='ProcessTrack_product', to='Product.Product', verbose_name='Product'),
            preserve_default=False,
        ),
    ]
