# Generated by Django 2.1.8 on 2020-01-17 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0006_processtrack_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processtrack',
            name='Step',
            field=models.ForeignKey(limit_choices_to={'active_status': '1'}, on_delete=django.db.models.deletion.CASCADE, related_name='ProcessTrack_step', to='kitchen.StepToprocess', verbose_name='Product'),
        ),
    ]
