# Generated by Django 2.1.8 on 2020-01-19 12:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0007_auto_20200117_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steptoprocess',
            name='time_of_process',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='Time Of Process'),
        ),
    ]
