# Generated by Django 2.1.8 on 2020-01-21 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0008_auto_20200119_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processtrack',
            name='process_status',
            field=models.CharField(blank=True, choices=[('0', 'Completed'), ('1', 'In Progress'), ('2', 'Not Started')], max_length=100, null=True, verbose_name='Process Status'),
        ),
        migrations.AlterField(
            model_name='steptoprocess',
            name='varient',
            field=models.ForeignKey(blank=True, limit_choices_to={'active_status': '1'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='StepToprocess_varient', to='Product.Variant', verbose_name='Variant'),
        ),
    ]
