# Generated by Django 2.1.8 on 2020-01-22 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0010_auto_20200122_1038'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processtrack',
            options={'verbose_name': 'Process Track', 'verbose_name_plural': ' Process Track'},
        ),
        migrations.AlterModelOptions(
            name='steptoprocess',
            options={'verbose_name': 'Step To process', 'verbose_name_plural': ' Steps To Process'},
        ),
        migrations.AlterField(
            model_name='processtrack',
            name='Order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProcessTrack_Order', to='Orders.Order', verbose_name='Order'),
        ),
    ]
