# Generated by Django 2.1.8 on 2020-03-03 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0011_auto_20200122_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processtrack',
            name='Step',
            field=models.ForeignKey(limit_choices_to={'active_status': '1'}, on_delete=django.db.models.deletion.CASCADE, related_name='ProcessTrack_step', to='kitchen.StepToprocess', verbose_name='Step'),
        ),
    ]
