# Generated by Django 2.1.8 on 2020-02-17 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Brands', '0006_company_is_sound'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_id', models.CharField(max_length=255, verbose_name='API Reference Id')),
                ('is_synced', models.BooleanField(default=0, verbose_name='Is Synced')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date & Time')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Updation Date & Time')),
                ('company', models.ForeignKey(limit_choices_to={'active_status': '1'}, on_delete=django.db.models.deletion.CASCADE, related_name='APIReference_Company', to='Brands.Company', verbose_name='Company')),
            ],
            options={
                'verbose_name': '   API Service Status',
                'verbose_name_plural': '   API Service Status',
            },
        ),
        migrations.CreateModel(
            name='EventTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=255, verbose_name='Event Type')),
                ('event_type_desc', models.CharField(blank=True, max_length=255, null=True, verbose_name='Event Type Description')),
                ('active_status', models.BooleanField(default=1, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date & Time')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Updation Date & Time')),
                ('company', models.ForeignKey(limit_choices_to={'active_status': '1'}, on_delete=django.db.models.deletion.CASCADE, related_name='EventTypes_Company', to='Brands.Company', verbose_name='Company')),
            ],
            options={
                'verbose_name': '   Event Type',
                'verbose_name_plural': '   Event Types',
            },
        ),
        migrations.CreateModel(
            name='UrbanCred',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=50, null=True, verbose_name='User Name')),
                ('apikey', models.CharField(blank=True, max_length=50, null=True, verbose_name='API Key')),
                ('active_status', models.BooleanField(default=1, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date & Time')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Updation Date & Time')),
                ('company', models.ForeignKey(limit_choices_to={'active_status': '1'}, on_delete=django.db.models.deletion.CASCADE, related_name='UrbanCred_Company', to='Brands.Company', verbose_name='Company')),
            ],
            options={
                'verbose_name': '   Account Credential',
                'verbose_name_plural': '   Account Credential',
            },
        ),
        migrations.CreateModel(
            name='webHooks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('callbackurl', models.CharField(max_length=255, verbose_name='Call Back Url')),
                ('active_status', models.BooleanField(default=1, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date & Time')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Updation Date & Time')),
                ('company', models.ForeignKey(limit_choices_to={'active_status': '1'}, on_delete=django.db.models.deletion.CASCADE, related_name='webHooks_Company', to='Brands.Company', verbose_name='Company')),
                ('event_type', models.ForeignKey(limit_choices_to={'active_status': '1'}, on_delete=django.db.models.deletion.CASCADE, related_name='webHooks_event_type', to='urbanpiper.EventTypes', verbose_name='Event Type')),
            ],
            options={
                'verbose_name': '   WebHook Setting',
                'verbose_name_plural': '   WebHook Setting',
            },
        ),
    ]
