# Generated by Django 2.1.8 on 2020-02-17 14:58

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Brands', '0006_company_is_sound'),
        ('urbanpiper', '0003_auto_20200217_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhooks',
            name='api_response',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='webhooks',
            unique_together={('company', 'event_type')},
        ),
    ]
