# Generated by Django 2.1.8 on 2020-02-18 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('urbanpiper', '0004_auto_20200217_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outletsync',
            name='ref_id',
            field=models.ForeignKey(blank=True, limit_choices_to={'active_status': '1'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='OutletSync_ref', to='urbanpiper.APIReference', verbose_name='API Reference Id'),
        ),
    ]
