# Generated by Django 2.1.8 on 2020-02-19 07:40

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urbanpiper', '0005_auto_20200218_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhooks',
            name='error_api_response',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
