# Generated by Django 2.1.8 on 2020-02-19 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbanpiper', '0006_webhooks_error_api_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='outletsync',
            name='action_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Sync Date & Time'),
        ),
        migrations.AlterField(
            model_name='outletsync',
            name='sync_status',
            field=models.CharField(choices=[('not_intiated', 'Not Initiated'), ('in_progress', 'In Progress'), ('synced', 'Synced')], default='not_intiated', max_length=50, verbose_name='Sync Status'),
        ),
    ]
