# Generated by Django 2.1.8 on 2020-02-21 12:19

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Brands', '0006_company_is_sound'),
        ('urbanpiper', '0009_auto_20200219_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawApiResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_response', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('url', models.CharField(max_length=255, verbose_name='Url of Event')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date & Time')),
                ('company', models.ForeignKey(limit_choices_to={'active_status': '1'}, on_delete=django.db.models.deletion.CASCADE, related_name='RawApiResponse_Company', to='Brands.Company', verbose_name='Company')),
            ],
            options={
                'verbose_name': '   Raw ApiResponse',
                'verbose_name_plural': '   Raw Api Response',
            },
        ),
    ]
