# Generated by Django 2.1.8 on 2020-02-21 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbanpiper', '0010_rawapiresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawapiresponse',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Url of Event'),
        ),
    ]
