# Generated by Django 2.1.8 on 2020-02-21 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('urbanpiper', '0011_auto_20200221_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawapiresponse',
            name='ref_id',
            field=models.ForeignKey(blank=True, limit_choices_to={'active_status': '1'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RawApiResponse_ref', to='urbanpiper.APIReference', verbose_name='API Reference Id'),
        ),
    ]
