# Generated by Django 2.1.8 on 2020-02-21 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbanpiper', '0013_outletsync_urban_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outletsync',
            name='urban_event',
            field=models.CharField(blank=True, choices=[('updated', 'Store Updated'), ('created', 'Store Created')], max_length=50, null=True, verbose_name='Event At UrbanPiper'),
        ),
    ]
