# Generated by Django 2.1.8 on 2020-02-21 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('urbanpiper', '0014_auto_20200221_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outletsync',
            name='ref_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='OutletSync_ref', to='urbanpiper.APIReference', verbose_name='API Reference Id'),
        ),
        migrations.AlterField(
            model_name='rawapiresponse',
            name='ref_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RawApiResponse_ref', to='urbanpiper.APIReference', verbose_name='API Reference Id'),
        ),
    ]
