# Generated by Django 2.1.8 on 2020-02-24 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Brands', '0006_company_is_sound'),
        ('urbanpiper', '0015_auto_20200221_1933'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionSync',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=0, verbose_name='Is Synced')),
                ('urban_event', models.CharField(blank=True, choices=[('enabled', 'Store Enabled'), ('disabled', 'Store Disabled')], max_length=50, null=True, verbose_name='Event At UrbanPiper')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date & Time')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Updation Date & Time')),
                ('company', models.ForeignKey(limit_choices_to={'active_status': '1'}, on_delete=django.db.models.deletion.CASCADE, related_name='ActionSync_Company', to='Brands.Company', verbose_name='Company')),
                ('ref_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ActionSync_ref', to='urbanpiper.APIReference', verbose_name='API Reference Id')),
                ('sync_outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ActionSync_outlet', to='urbanpiper.OutletSync', verbose_name='Synced Outlet')),
            ],
            options={
                'verbose_name': '   Synced Outlet Status',
                'verbose_name_plural': '   Synced Outlet Status',
            },
        ),
    ]
