# Generated by Django 2.1.8 on 2020-02-26 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbanpiper', '0017_catsync_productsync'),
    ]

    operations = [
        migrations.AddField(
            model_name='catsync',
            name='sync_status',
            field=models.CharField(choices=[('not_intiated', 'Not Initiated'), ('in_progress', 'In Progress'), ('synced', 'Synced')], default='not_intiated', max_length=50, verbose_name='Sync Status'),
        ),
        migrations.AddField(
            model_name='productsync',
            name='sync_status',
            field=models.CharField(choices=[('not_intiated', 'Not Initiated'), ('in_progress', 'In Progress'), ('synced', 'Synced')], default='not_intiated', max_length=50, verbose_name='Sync Status'),
        ),
    ]
