# Generated by Django 2.1.8 on 2020-03-04 14:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbanpiper', '0019_productsync_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsync',
            name='addpn_grp_association',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='productsync',
            name='discount_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Discount Product Price'),
        ),
        migrations.AddField(
            model_name='productsync',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='Product Price'),
        ),
    ]
