# Generated by Django 2.1.8 on 2020-03-05 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Outlet', '0007_outletprofile_user_type'),
        ('urbanpiper', '0020_auto_20200304_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='apireference',
            name='outlet',
            field=models.ForeignKey(blank=True, limit_choices_to={'active_status': '1'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='APIReference_outlet', to='Outlet.OutletProfile', verbose_name='Outlet'),
        ),
    ]
