# Generated by Django 2.1.8 on 2020-03-17 08:52

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Outlet', '0007_outletprofile_user_type'),
        ('Brands', '0007_company_is_open'),
        ('urbanpiper', '0021_apireference_outlet'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderRawApiResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_response', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date & Time')),
                ('company', models.ForeignKey(limit_choices_to={'active_status': '1'}, on_delete=django.db.models.deletion.CASCADE, related_name='OrderRawApiResponse_Company', to='Brands.Company', verbose_name='Company')),
                ('sync_outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OrderRawApiResponse_outlet', to='urbanpiper.OutletSync', verbose_name='Synced Outlet')),
            ],
            options={
                'verbose_name': '   Order Relay Raw Api Response',
                'verbose_name_plural': '   Order Relay Raw Api Response',
            },
        ),
        migrations.CreateModel(
            name='UrbanOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=150, null=True, verbose_name='Order Id')),
                ('customer_address', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Customer Address Details')),
                ('customer_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Customer Details')),
                ('next_states', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None, verbose_name='Next Possible Status')),
                ('next_state', models.CharField(blank=True, max_length=150, null=True, verbose_name='Next Expected State')),
                ('order_state', models.CharField(blank=True, max_length=150, null=True, verbose_name='Current State')),
                ('source', models.CharField(blank=True, max_length=150, null=True, verbose_name='Channel')),
                ('order_description', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Order Description')),
                ('total_items', models.PositiveIntegerField(blank=True, null=True, verbose_name='Total Items')),
                ('discount_value', models.FloatField(blank=True, null=True, verbose_name='Discount Value')),
                ('sub_total', models.FloatField(blank=True, null=True, verbose_name='Sub Total')),
                ('total_bill_value', models.FloatField(blank=True, null=True, verbose_name='Total Payable Amount')),
                ('packing_charge', models.FloatField(blank=True, max_length=99999.99, null=True, verbose_name='Packing Charge')),
                ('delivery_charge', models.FloatField(blank=True, max_length=99999.99, null=True, verbose_name='Delivery Charge')),
                ('order_level_total_taxes', models.FloatField(blank=True, max_length=99999.99, null=True, verbose_name='Total Tax')),
                ('order_level_total_charges', models.FloatField(blank=True, max_length=99999.99, null=True, verbose_name='Total Charge')),
                ('item_level_total_charges', models.FloatField(blank=True, max_length=99999.99, null=True, verbose_name='Total Charge Item Level')),
                ('item_level_total_taxes', models.FloatField(blank=True, max_length=99999.99, null=True, verbose_name='Total Tax Item Level')),
                ('order_type', models.CharField(blank=True, max_length=150, null=True, verbose_name='Order Type')),
                ('final_payment', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Final Payment')),
                ('coupon_code', models.CharField(blank=True, max_length=150, null=True, verbose_name='Coupon Code')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date & Time')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Updation Date & Time')),
                ('Company', models.ForeignKey(limit_choices_to={'active_status': '1'}, on_delete=django.db.models.deletion.CASCADE, related_name='UrbanOrders_Company', to='Brands.Company', verbose_name='Company')),
                ('outlet', models.ForeignKey(blank=True, limit_choices_to={'active_status': '1'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UrbanOrders_OutletProfile', to='Outlet.OutletProfile', verbose_name='Outlet')),
            ],
            options={
                'verbose_name': 'Urban Order Management',
                'verbose_name_plural': ' Urban Order Management',
            },
        ),
    ]
