# Generated by Django 2.1.8 on 2020-03-23 04:54

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Brands', '0007_company_is_open'),
        ('urbanpiper', '0022_orderrawapiresponse_urbanorders'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatusRawApiResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_response', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date & Time')),
                ('company', models.ForeignKey(limit_choices_to={'active_status': '1'}, on_delete=django.db.models.deletion.CASCADE, related_name='OrderStatusRawApi_Company', to='Brands.Company', verbose_name='Company')),
                ('sync_outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OrderStatusRawApi_outlet', to='urbanpiper.OutletSync', verbose_name='Synced Outlet')),
            ],
            options={
                'verbose_name': '   Order Status Update Raw Api Response',
                'verbose_name_plural': '   Order Status Update Raw Api Response',
            },
        ),
        migrations.CreateModel(
            name='RiderStatusRawApiResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_response', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date & Time')),
                ('company', models.ForeignKey(limit_choices_to={'active_status': '1'}, on_delete=django.db.models.deletion.CASCADE, related_name='RiderStatusRawApi_Company', to='Brands.Company', verbose_name='Company')),
                ('sync_outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RiderStatusRawApi_outlet', to='urbanpiper.OutletSync', verbose_name='Synced Outlet')),
            ],
            options={
                'verbose_name': '   Rider Status Update Raw Api Response',
                'verbose_name_plural': '   Rider Status Update Raw Api Response',
            },
        ),
    ]
