# Generated by Django 2.1.8 on 2020-03-25 17:59

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('urbanpiper', '0023_orderstatusrawapiresponse_riderstatusrawapiresponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatOutletWise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urban_event', models.CharField(blank=True, choices=[('created', 'Category Created'), ('updated', 'Category Updated')], max_length=50, null=True, verbose_name='Event At UrbanPiper')),
                ('sync_status', models.CharField(choices=[('not_intiated', 'Not Initiated'), ('in_progress', 'In Progress'), ('synced', 'Synced')], default='not_intiated', max_length=50, verbose_name='Sync Status')),
                ('is_enabled', models.BooleanField(default=0, verbose_name='Is Synced')),
                ('is_available', models.BooleanField(default=0, verbose_name='Is Available')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date & Time')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Updation Date & Time')),
            ],
            options={
                'verbose_name': '   Synced Outlet Wise Category',
                'verbose_name_plural': '  Synced Outlet Wise Categories',
            },
        ),
        migrations.CreateModel(
            name='ProductOutletWise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urban_event', models.CharField(blank=True, choices=[('created', 'Product Created'), ('updated', 'Product Updated')], max_length=50, null=True, verbose_name='Event At UrbanPiper')),
                ('sync_status', models.CharField(choices=[('not_intiated', 'Not Initiated'), ('in_progress', 'In Progress'), ('synced', 'Synced')], default='not_intiated', max_length=50, verbose_name='Sync Status')),
                ('is_enabled', models.BooleanField(default=0, verbose_name='Is Synced')),
                ('is_available', models.BooleanField(default=0, verbose_name='Is Available')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date & Time')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Updation Date & Time')),
                ('sync_outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProductOutletWise_outlet', to='urbanpiper.OutletSync', verbose_name='Synced Outlet')),
            ],
            options={
                'verbose_name': '   Synced Outlet Wise Product',
                'verbose_name_plural': '  Synced Outlet Wise Products',
            },
        ),
        migrations.RemoveField(
            model_name='catsync',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='catsync',
            name='is_enabled',
        ),
        migrations.RemoveField(
            model_name='catsync',
            name='sync_outlet',
        ),
        migrations.RemoveField(
            model_name='catsync',
            name='sync_status',
        ),
        migrations.RemoveField(
            model_name='catsync',
            name='urban_event',
        ),
        migrations.RemoveField(
            model_name='productsync',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='productsync',
            name='is_enabled',
        ),
        migrations.RemoveField(
            model_name='productsync',
            name='sync_outlet',
        ),
        migrations.RemoveField(
            model_name='productsync',
            name='sync_status',
        ),
        migrations.RemoveField(
            model_name='productsync',
            name='urban_event',
        ),
        migrations.AddField(
            model_name='catsync',
            name='outlet_map',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None, verbose_name='Outlet Mapped Ids'),
        ),
        migrations.AddField(
            model_name='productsync',
            name='outlet_map',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None, verbose_name='Outlet Mapped Ids'),
        ),
        migrations.AddField(
            model_name='productoutletwise',
            name='sync_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProductOutletWise_ProductSync', to='urbanpiper.ProductSync', verbose_name='Synced Product'),
        ),
        migrations.AddField(
            model_name='catoutletwise',
            name='sync_cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CatOutletWise_CatSync', to='urbanpiper.CatSync', verbose_name='Synced Category'),
        ),
        migrations.AddField(
            model_name='catoutletwise',
            name='sync_outlet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CatOutletWise_outlet', to='urbanpiper.OutletSync', verbose_name='Synced Outlet'),
        ),
    ]
