# Generated by Django 2.1.8 on 2020-03-28 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbanpiper', '0026_auto_20200327_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoutletwise',
            name='product_status',
            field=models.CharField(choices=[('enabled', 'Enabled'), ('disabled', 'Disabled'), ('in_progress', 'In Progress')], default='enabled', max_length=50, verbose_name='Product Status'),
        ),
    ]
