# Generated by Django 2.1.8 on 2020-04-04 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbanpiper', '0027_auto_20200328_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='urbanorders',
            name='special_instructions',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Special Instructions'),
        ),
        migrations.AddField(
            model_name='urbanorders',
            name='total_tax',
            field=models.FloatField(blank=True, max_length=99999.99, null=True, verbose_name='Total Tax'),
        ),
        migrations.AlterField(
            model_name='urbanorders',
            name='order_level_total_taxes',
            field=models.FloatField(blank=True, max_length=99999.99, null=True, verbose_name='Order level Total Tax'),
        ),
    ]
