# Generated by Django 2.1.8 on 2020-04-13 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbanpiper', '0028_auto_20200404_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='urbanorders',
            name='channel_order_id',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Channel Order Id'),
        ),
    ]
