# Generated by Django 2.1.8 on 2020-04-22 06:20

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Brands', '0007_company_is_open'),
        ('Outlet', '0014_remove_outletprofile_status'),
        ('urbanpiper', '0029_urbanorders_channel_order_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuPayload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Payload')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date & Time')),
                ('company', models.ForeignKey(limit_choices_to={'active_status': '1'}, on_delete=django.db.models.deletion.CASCADE, related_name='MenuPayload_Company', to='Brands.Company', verbose_name='Company')),
                ('outlet', models.ForeignKey(limit_choices_to={'active_status': '1'}, on_delete=django.db.models.deletion.CASCADE, related_name='MenuPayload_outlet', to='Outlet.OutletProfile', verbose_name='Outlet')),
            ],
            options={
                'verbose_name': '   Menu Payload',
                'verbose_name_plural': '   Menu Payload',
            },
        ),
    ]
