# Generated by Django 2.1.8 on 2020-04-22 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbanpiper', '0030_menupayload'),
    ]

    operations = [
        migrations.AddField(
            model_name='catsync',
            name='active_status',
            field=models.BooleanField(default=0, verbose_name='Is Active'),
        ),
        migrations.AddField(
            model_name='productoutletwise',
            name='active_status',
            field=models.BooleanField(default=0, verbose_name='Is Active'),
        ),
        migrations.AddField(
            model_name='productsync',
            name='active_status',
            field=models.BooleanField(default=0, verbose_name='Is Active'),
        ),
    ]
