# Generated by Django 2.1.8 on 2020-05-22 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbanpiper', '0031_auto_20200422_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urbanorders',
            name='special_instructions',
            field=models.TextField(blank=True, null=True, verbose_name='Special Instructions'),
        ),
    ]
