# Generated by Django 2.1.8 on 2020-06-10 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbanpiper', '0032_auto_20200522_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='catoutletwise',
            name='priority',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Priority'),
        ),
    ]
