# Generated by Django 2.1.8 on 2020-06-24 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbanpiper', '0033_catoutletwise_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='menupayload',
            name='plateform',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Plateform'),
        ),
    ]
