# Generated by Django 2.1.8 on 2020-06-24 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbanpiper', '0034_menupayload_plateform'),
    ]

    operations = [
        migrations.AddField(
            model_name='catoutletwise',
            name='urbanpiper_id',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='UrbanPiper Id'),
        ),
        migrations.AddField(
            model_name='productsync',
            name='urbanpiper_id',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='UrbanPiper Id'),
        ),
    ]
