# Generated by Django 2.1.8 on 2020-07-01 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0039_auto_20200515_2048'),
        ('urbanpiper', '0035_auto_20200624_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsync',
            name='sub_category',
            field=models.ForeignKey(blank=True, limit_choices_to={'active_status': '1'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ProductSync_sub_category', to='Product.ProductsubCategory', verbose_name='Sub Category'),
        ),
    ]
