# Generated by Django 2.1.8 on 2020-07-09 02:22

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0039_auto_20200515_2048'),
        ('Brands', '0007_company_is_open'),
        ('urbanpiper', '0036_productsync_sub_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCatOutletWise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urbanpiper_id', models.CharField(blank=True, max_length=150, null=True, verbose_name='UrbanPiper Id')),
                ('urban_event', models.CharField(blank=True, choices=[('created', 'Sub Category Created'), ('updated', 'Sub Category Updated')], max_length=50, null=True, verbose_name='Event At UrbanPiper')),
                ('sync_status', models.CharField(choices=[('not_intiated', 'Not Initiated'), ('in_progress', 'In Progress'), ('synced', 'Synced')], default='not_intiated', max_length=50, verbose_name='Sync Status')),
                ('is_enabled', models.BooleanField(default=0, verbose_name='Is Synced')),
                ('is_available', models.BooleanField(default=0, verbose_name='Is Available')),
                ('priority', models.PositiveIntegerField(blank=True, null=True, verbose_name='Priority')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date & Time')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Updation Date & Time')),
                ('sync_outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_CatOutletWise_outlet', to='urbanpiper.OutletSync', verbose_name='Synced Outlet')),
            ],
            options={
                'verbose_name': '   Synced Outlet Wise Sub Category',
                'verbose_name_plural': '  Synced Outlet Wise Sub Categories',
            },
        ),
        migrations.CreateModel(
            name='SubCatSync',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outlet_map', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None, verbose_name='Outlet Mapped Ids')),
                ('active_status', models.BooleanField(default=0, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date & Time')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Updation Date & Time')),
                ('company', models.ForeignKey(limit_choices_to={'active_status': '1'}, on_delete=django.db.models.deletion.CASCADE, related_name='SubCatSync_Company', to='Brands.Company', verbose_name='Company')),
                ('sub_category', models.ForeignKey(limit_choices_to={'active_status': '1'}, on_delete=django.db.models.deletion.CASCADE, related_name='SubCatSync_subcategory', to='Product.ProductsubCategory', verbose_name='Sub Category')),
            ],
            options={
                'verbose_name': '   Synced Sub Category',
                'verbose_name_plural': '  Synced Sub Categories',
            },
        ),
        migrations.AddField(
            model_name='subcatoutletwise',
            name='sync_sub_cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subCatOutletWise_SubCatSync', to='urbanpiper.SubCatSync', verbose_name='Synced Sub Category'),
        ),
    ]
