# Generated by Django 2.1.8 on 2020-07-12 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urbanpiper', '0037_auto_20200709_0752'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actionsync',
            options={'verbose_name': '   Synced Outlet Status', 'verbose_name_plural': '          Synced Outlet Status'},
        ),
        migrations.AlterModelOptions(
            name='apireference',
            options={'verbose_name': '   API Service Status', 'verbose_name_plural': '                 API Service Status'},
        ),
        migrations.AlterModelOptions(
            name='catoutletwise',
            options={'verbose_name': '   Synced Outlet Wise Category', 'verbose_name_plural': '       Synced Outlet Wise Categories'},
        ),
        migrations.AlterModelOptions(
            name='catsync',
            options={'verbose_name': '   Synced Category', 'verbose_name_plural': '         Synced Categories'},
        ),
        migrations.AlterModelOptions(
            name='eventtypes',
            options={'verbose_name': '    Event Type', 'verbose_name_plural': '                   Event Types'},
        ),
        migrations.AlterModelOptions(
            name='menupayload',
            options={'verbose_name': '   Menu Payload', 'verbose_name_plural': '                Menu Payload'},
        ),
        migrations.AlterModelOptions(
            name='orderrawapiresponse',
            options={'verbose_name': '   Order Relay Raw Api Response', 'verbose_name_plural': '             Order Relay Raw Api Response'},
        ),
        migrations.AlterModelOptions(
            name='orderstatusrawapiresponse',
            options={'verbose_name': '   Order Status Update Raw Api Response', 'verbose_name_plural': '            Order Status Update Raw Api Response'},
        ),
        migrations.AlterModelOptions(
            name='outletsync',
            options={'verbose_name': '   Outlet Sync Status', 'verbose_name_plural': '              Outlet Sync Status'},
        ),
        migrations.AlterModelOptions(
            name='productoutletwise',
            options={'verbose_name': '   Synced Outlet Wise Product', 'verbose_name_plural': '    Synced Outlet Wise Products'},
        ),
        migrations.AlterModelOptions(
            name='productsync',
            options={'verbose_name': '   Synced Product', 'verbose_name_plural': '      Synced Products'},
        ),
        migrations.AlterModelOptions(
            name='rawapiresponse',
            options={'verbose_name': '   Raw ApiResponse', 'verbose_name_plural': '               Raw Api Response'},
        ),
        migrations.AlterModelOptions(
            name='riderstatusrawapiresponse',
            options={'verbose_name': '   Rider Status Update Raw Api Response', 'verbose_name_plural': '           Rider Status Update Raw Api Response'},
        ),
        migrations.AlterModelOptions(
            name='subcatoutletwise',
            options={'verbose_name': '   Synced Outlet Wise Sub Category', 'verbose_name_plural': '      Synced Outlet Wise Sub Categories'},
        ),
        migrations.AlterModelOptions(
            name='subcatsync',
            options={'verbose_name': '   Synced Sub Category', 'verbose_name_plural': '        Synced Sub Categories'},
        ),
        migrations.AlterModelOptions(
            name='urbancred',
            options={'verbose_name': '    Account Credential', 'verbose_name_plural': '                    Account Credential'},
        ),
        migrations.AlterModelOptions(
            name='urbanorders',
            options={'verbose_name': 'Urban Order Management', 'verbose_name_plural': '   Urban Order Management'},
        ),
        migrations.AlterModelOptions(
            name='webhooks',
            options={'verbose_name': '    WebHook Setting', 'verbose_name_plural': '                  WebHook Setting'},
        ),
    ]
