# Generated by Django 2.1.8 on 2020-07-22 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbanpiper', '0038_auto_20200712_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='urbanorders',
            name='external_tax',
            field=models.FloatField(blank=True, max_length=99999.99, null=True, verbose_name='External Tax'),
        ),
    ]
