# Generated by Django 2.1.8 on 2020-07-22 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbanpiper', '0039_urbanorders_external_tax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urbanorders',
            name='external_tax',
        ),
        migrations.AddField(
            model_name='urbanorders',
            name='external_discount',
            field=models.FloatField(blank=True, max_length=99999.99, null=True, verbose_name='External Discount'),
        ),
    ]
