# Generated by Django 2.1.8 on 2020-08-30 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbanpiper', '0040_auto_20200722_0830'),
    ]

    operations = [
        migrations.CreateModel(
            name='zomatoMenuTemporaryData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zomato_product_id', models.CharField(blank=True, max_length=150, null=True, verbose_name='Zomato Product Id')),
                ('addon_grp', models.CharField(blank=True, max_length=150, null=True, verbose_name='Zomato Addon Group Id')),
            ],
            options={
                'verbose_name': '   zomatoMenuTemporaryData',
                'verbose_name_plural': '    zomatoMenuTemporaryData',
            },
        ),
    ]
