# Generated by Django 2.1.8 on 2020-08-31 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbanpiper', '0041_zomatomenutemporarydata'),
    ]

    operations = [
        migrations.CreateModel(
            name='zomatoMenuTempAddonGrpData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zomato_addon_grp_id', models.CharField(blank=True, max_length=150, null=True, verbose_name='Zomato Addon Group Id')),
            ],
            options={
                'verbose_name': '   zomatoMenuTempAddonGrpData',
                'verbose_name_plural': '    zomatoMenuTempAddonGrpData',
            },
        ),
        migrations.CreateModel(
            name='zomatoMenuTempAllAddonData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zomato_addon_grp_id', models.CharField(blank=True, max_length=150, null=True, verbose_name='Zomato Addon Group Id')),
                ('zomato_addon_id', models.CharField(blank=True, max_length=150, null=True, verbose_name='Zomato Addon Id')),
            ],
            options={
                'verbose_name': '   zomatoMenuTempAllAddonData',
                'verbose_name_plural': '    zomatoMenuTempAllAddonData',
            },
        ),
        migrations.CreateModel(
            name='zomatoMenuTempOptionData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zomato_product_id', models.CharField(blank=True, max_length=150, null=True, verbose_name='Zomato Product Id')),
            ],
            options={
                'verbose_name': '   zomatoMenuTempOptionData',
                'verbose_name_plural': '    zomatoMenuTempOptionData',
            },
        ),
        migrations.CreateModel(
            name='zomatoMenuTemporaryItemData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zomato_product_id', models.CharField(blank=True, max_length=150, null=True, verbose_name='Zomato Product Id')),
            ],
            options={
                'verbose_name': '   zomatoMenuTemporaryItemData',
                'verbose_name_plural': '    zomatoMenuTemporaryItemData',
            },
        ),
        migrations.RenameModel(
            old_name='zomatoMenuTemporaryData',
            new_name='zomatoMenuTemporaryAddonData',
        ),
        migrations.AlterModelOptions(
            name='zomatomenutemporaryaddondata',
            options={'verbose_name': '   zomatoMenuTemporaryAddonData', 'verbose_name_plural': '    zomatoMenuTemporaryAddonData'},
        ),
    ]
