# Generated by Django 2.1.8 on 2020-12-11 08:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbanpiper', '0044_subcatoutletwiseaddongroup_subcatoutletwiseaddons'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempzomatoNestedCrust',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zomato_addon_crust_grp_id', models.CharField(blank=True, max_length=150, null=True, verbose_name='Zomato Addon Crust Group Id')),
                ('zomato_addon_id', models.CharField(blank=True, max_length=150, null=True, verbose_name='Zomato Addon Id')),
                ('nested_grp_ids', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None, verbose_name='Nested Mapped Ids')),
            ],
            options={
                'verbose_name': '   TempzomatoNestedCrust',
                'verbose_name_plural': '    TempzomatoNestedCrust',
            },
        ),
    ]
