# Generated by Django 2.1.8 on 2020-12-11 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0053_auto_20201211_1434'),
        ('urbanpiper', '0045_tempzomatonestedcrust'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsync',
            name='zomato_crust_id',
            field=models.ForeignKey(blank=True, limit_choices_to={'active_status': '1'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ProductSync_AddonDetails', to='Product.AddonDetails', verbose_name='Zomato Crust Id'),
        ),
    ]
