# Generated by Django 2.1.8 on 2020-12-16 14:20

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbanpiper', '0046_productsync_zomato_crust_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveOrderLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Request Data')),
                ('response_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Response Data')),
                ('run_time', models.FloatField(blank=True, null=True, verbose_name='Execution Time')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date & Time')),
            ],
            options={
                'verbose_name': 'Live Order Log',
                'verbose_name_plural': 'Live Order Log',
            },
        ),
        migrations.CreateModel(
            name='OrderStatusLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Request Data')),
                ('response_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Response Data')),
                ('run_time', models.FloatField(blank=True, null=True, verbose_name='Execution Time')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date & Time')),
            ],
            options={
                'verbose_name': 'Order Status Update Log',
                'verbose_name_plural': 'Order Status Update Log',
            },
        ),
        migrations.CreateModel(
            name='RiderStatusLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Request Data')),
                ('response_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Response Data')),
                ('run_time', models.FloatField(blank=True, null=True, verbose_name='Execution Time')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date & Time')),
            ],
            options={
                'verbose_name': 'Rider Status Update Log',
                'verbose_name_plural': 'Rider Status Update Log',
            },
        ),
    ]
