# Generated by Django 2.1.8 on 2020-12-16 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbanpiper', '0047_liveorderlog_orderstatuslog_riderstatuslog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liveorderlog',
            name='run_time',
            field=models.FloatField(blank=True, null=True, verbose_name='Execution Time in MS'),
        ),
        migrations.AlterField(
            model_name='orderstatuslog',
            name='run_time',
            field=models.FloatField(blank=True, null=True, verbose_name='Execution Time in MS'),
        ),
        migrations.AlterField(
            model_name='riderstatuslog',
            name='run_time',
            field=models.FloatField(blank=True, null=True, verbose_name='Execution Time in MS'),
        ),
    ]
