# Generated by Django 2.1.8 on 2021-01-22 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbanpiper', '0048_auto_20201216_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urbanorders',
            name='order_id',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True, verbose_name='Order Id'),
        ),
    ]
