# Generated by Django 2.1.8 on 2021-02-25 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('urbanpiper', '0049_auto_20210122_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menupayload',
            name='outlet',
            field=models.ForeignKey(blank=True, limit_choices_to={'active_status': '1'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MenuPayload_outlet', to='Outlet.OutletProfile', verbose_name='Outlet'),
        ),
    ]
