# Generated by Django 2.1.8 on 2019-11-24 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_bill_value',
            field=models.FloatField(blank=True, null=True, verbose_name='Total Payable Amount'),
        ),
    ]
