# Generated by Django 2.1.8 on 2019-11-27 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0002_auto_20191124_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_completed',
            field=models.BooleanField(default=0, verbose_name='Is Completed'),
        ),
    ]
