# Generated by Django 2.1.8 on 2019-11-29 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0003_order_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='has_been_here',
            field=models.BooleanField(default=0, verbose_name='Has Been Here'),
        ),
    ]
