# Generated by Django 2.1.8 on 2019-11-29 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Outlet', '0005_auto_20191128_2052'),
        ('Orders', '0004_order_has_been_here'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_boy',
            field=models.ForeignKey(blank=True, limit_choices_to={'active_status': '1'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='Outlet.DeliveryBoy', verbose_name='Delivery Boy'),
        ),
    ]
