# Generated by Django 2.1.8 on 2019-11-29 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0005_order_delivery_boy'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderTracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_status', models.BooleanField(default=1, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date & Time')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Updation Date & Time')),
                ('Order_staus_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OrderTracking_order_status', to='Orders.OrderStatusType', verbose_name='Order Status')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OrderTracking_order', to='Orders.Order', verbose_name='Order Tracking')),
            ],
            options={
                'verbose_name': 'Order Tracking',
                'verbose_name_plural': '  Order Tracking',
            },
        ),
    ]
