# Generated by Django 2.1.8 on 2019-12-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0006_ordertracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstatustype',
            name='color_code',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Color Code'),
        ),
    ]
