# Generated by Django 2.1.8 on 2019-12-03 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0008_auto_20191203_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_seen',
            field=models.BooleanField(default=0, verbose_name='Is Seen'),
        ),
    ]
