# Generated by Django 2.1.8 on 2020-02-25 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0010_orderstatustype_can_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_accepted',
            field=models.BooleanField(default=0, verbose_name='Is Accepted'),
        ),
    ]
