# Generated by Django 2.1.8 on 2020-02-29 09:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0030_addons_updated_at'),
        ('Orders', '0011_order_is_accepted'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuantityWiseOrderProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)], verbose_name='Priority')),
                ('active_status', models.BooleanField(default=0, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date & Time')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Updation Date & Time')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='QuantityWiseOrderProcess_order', to='Orders.Order', verbose_name='Order id')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='QuantityWiseOrderProcess_product', to='Product.Product', verbose_name='product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='QuantityWiseOrderProcess_product', to='Product.Variant', verbose_name='variant')),
            ],
            options={
                'verbose_name': 'Order QuantityWiseOrderProcess',
                'verbose_name_plural': 'Order QuantityWiseOrderProcess',
            },
        ),
    ]
