# Generated by Django 2.1.8 on 2020-03-04 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0013_order_payment_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_source',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Order Source'),
        ),
    ]
