# Generated by Django 2.1.8 on 2020-03-05 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0014_order_order_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_charge',
            field=models.FloatField(blank=True, max_length=99999.99, null=True, verbose_name='Delivery Charge'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Order Type'),
        ),
        migrations.AddField(
            model_name='order',
            name='packing_charge',
            field=models.FloatField(blank=True, max_length=99999.99, null=True, verbose_name='Packing Charge'),
        ),
    ]
