# Generated by Django 2.1.8 on 2020-03-19 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0016_auto_20200305_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Transaction Id'),
        ),
    ]
