# Generated by Django 2.1.8 on 2020-03-21 12:54

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0018_auto_20200319_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_cancel',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Order Cancel'),
        ),
        migrations.AddField(
            model_name='order',
            name='outlet_order_id',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Outlet Order Id'),
        ),
        migrations.AddField(
            model_name='order',
            name='tax_detail',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Tax Details'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='User'),
        ),
    ]
