# Generated by Django 2.1.8 on 2020-03-22 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0019_auto_20200321_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_Offers',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Discount Offers'),
        ),
    ]
