# Generated by Django 2.1.8 on 2020-03-22 09:10

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0020_order_discount_offers'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='settlement_details',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Settlement Details'),
        ),
    ]
