# Generated by Django 2.1.8 on 2020-03-22 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0022_auto_20200322_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[('0', 'Cash on Delivery'), ('1', 'Dineout'), ('2', 'Paytm'), ('3', 'Razorpay'), ('4', 'PayU'), ('5', 'EDC'), ('6', 'Mobiquik'), ('7', 'Mix'), ('8', 'EDC Amex'), ('9', 'EDC Yes Bank')], max_length=150, null=True, verbose_name='Payment Mode'),
        ),
    ]
