# Generated by Django 2.1.8 on 2020-03-23 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0023_auto_20200322_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Aggregator_order_status',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Aggregator Order Status'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_aggregator',
            field=models.BooleanField(default=0, verbose_name='Is Aggregator'),
        ),
        migrations.AddField(
            model_name='order',
            name='urban_order_id',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Aggregator Order ID'),
        ),
    ]
