# Generated by Django 2.1.8 on 2020-04-07 15:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0024_auto_20200323_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='check_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None, verbose_name='Outlet Mapped Ids'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_rider_assign',
            field=models.BooleanField(default=0, verbose_name='Is Accepted'),
        ),
    ]
