# Generated by Django 2.1.8 on 2020-04-07 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0026_auto_20200407_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='check_list',
        ),
    ]
