# Generated by Django 2.1.8 on 2020-04-10 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0027_remove_order_check_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_rider_assign',
            field=models.BooleanField(default=0, verbose_name='Is Rider Assign'),
        ),
    ]
