# Generated by Django 2.1.8 on 2020-04-11 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0028_auto_20200410_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancel_responsibility',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Cancel Responsibility'),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Discount Name'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_cancel_reason',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Order Cancel Reason'),
        ),
    ]
