# Generated by Django 2.1.8 on 2020-04-13 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0029_auto_20200411_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cancel_responsibility',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Cancel Responsibilityorder_description'),
        ),
    ]
