# Generated by Django 2.1.8 on 2020-04-13 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0030_auto_20200413_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='channel_order_id',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Channel Order Id'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cancel_responsibility',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Cancellation Description'),
        ),
    ]
