# Generated by Django 2.1.8 on 2020-04-16 16:52

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0032_auto_20200416_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_boy_details',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Delivery Boy Details'),
        ),
    ]
