# Generated by Django 2.1.8 on 2020-04-20 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0033_order_delivery_boy_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='synced',
            field=models.BooleanField(default=0, verbose_name='Is Synced'),
        ),
    ]
