# Generated by Django 2.1.8 on 2020-04-28 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0035_ordertracking_key_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[('0', 'Cash on Delivery'), ('1', 'Dineout'), ('2', 'Paytm'), ('3', 'Razorpay'), ('4', 'PayU'), ('5', 'EDC'), ('6', 'Mobiquik'), ('7', 'Mix'), ('8', 'EDC Amex'), ('9', 'EDC Yes Bank'), ('10', 'swiggy'), ('11', 'Z Prepaid'), ('12', 'S Prepaid')], max_length=150, null=True, verbose_name='Payment Mode'),
        ),
    ]
