# Generated by Django 2.1.8 on 2020-05-15 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0037_auto_20200505_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='aggregator_payment_mode',
            field=models.CharField(blank=True, choices=[('COD', 'COD'), ('Swiggy', 'Swiggy'), ('Zomato', 'Zomato')], max_length=150, null=True, verbose_name='Aggregator Payment Mode'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Delivery Type'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[('0', 'Cash on Delivery'), ('1', 'Dineout'), ('2', 'Paytm'), ('3', 'Razorpay'), ('4', 'PayU'), ('5', 'EDC'), ('6', 'Mobiquik'), ('7', 'zomato'), ('8', 'EDC Amex'), ('9', 'EDC Yes Bank'), ('10', 'swiggy'), ('11', 'Z Prepaid'), ('12', 'S Prepaid'), ('13', 'Dunzo')], max_length=150, null=True, verbose_name='Payment Mode'),
        ),
    ]
