# Generated by Django 2.1.8 on 2020-05-16 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0038_auto_20200515_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_reason',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Discount Reason'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[('0', 'Cash on Delivery'), ('1', 'Dineout'), ('2', 'Paytm'), ('3', 'Razorpay'), ('4', 'PayU'), ('5', 'EDC'), ('6', 'Mobiquik'), ('7', 'Mix'), ('8', 'EDC Amex'), ('9', 'EDC Yes Bank'), ('10', 'swiggy'), ('11', 'Z Prepaid'), ('12', 'S Prepaid'), ('13', 'Dunzo'), ('14', 'Zomato Cash'), ('15', 'Zomato')], max_length=150, null=True, verbose_name='Payment Mode'),
        ),
    ]
