# Generated by Django 2.1.8 on 2020-05-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0039_auto_20200516_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='special_instructions',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Special Instructions'),
        ),
    ]
