# Generated by Django 2.1.8 on 2020-06-04 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0041_auto_20200524_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertracking',
            name='kpt',
            field=models.FloatField(default=0, verbose_name='KPT'),
        ),
        migrations.AddField(
            model_name='ordertracking',
            name='kpt_to_dispatch',
            field=models.FloatField(default=0, verbose_name='KPT To Dispatch'),
        ),
        migrations.AddField(
            model_name='ordertracking',
            name='order_acceptance_time',
            field=models.FloatField(default=0, verbose_name='Order Acceptance Time'),
        ),
        migrations.AddField(
            model_name='ordertracking',
            name='ttk',
            field=models.FloatField(default=0, verbose_name='TTK'),
        ),
    ]
