# Generated by Django 2.1.8 on 2020-06-04 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0042_auto_20200604_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordertracking',
            name='kpt',
        ),
        migrations.RemoveField(
            model_name='ordertracking',
            name='kpt_to_dispatch',
        ),
        migrations.RemoveField(
            model_name='ordertracking',
            name='order_acceptance_time',
        ),
        migrations.RemoveField(
            model_name='ordertracking',
            name='ttk',
        ),
    ]
