# Generated by Django 2.1.8 on 2020-06-04 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0043_auto_20200604_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderProcessTimeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_acceptance_time', models.FloatField(default=0, verbose_name='Order Acceptance Time')),
                ('kpt', models.FloatField(default=0, verbose_name='KPT')),
                ('kpt_to_dispatch', models.FloatField(default=0, verbose_name='KPT To Dispatch')),
                ('ttk', models.FloatField(default=0, verbose_name='TTK')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OrderProcessTimeLog_order', to='Orders.Order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Order Process Time Log',
                'verbose_name_plural': 'Order Process Time Log',
            },
        ),
    ]
